"""Opt-in CUDA-only solvation/full-build smoke for direct conjugation artifacts."""

from __future__ import annotations

import math
import os
import shutil
import signal
import time
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pytest

GPU_ENV_VAR = "POLYZYMD_RUN_CONJUGATION_GPU_SOLVATION"
GPU_PADDING_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_PADDING_NM"
GPU_MINIMIZATION_ITERS_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_MIN_ITERS"
GPU_NVT_STEPS_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_NVT_STEPS"
GPU_MAX_SOLUTE_SPAN_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_MAX_SPAN_NM"
GPU_MAX_BOX_EDGE_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_MAX_BOX_EDGE_NM"
GPU_MAX_WATERS_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_MAX_WATERS"
GPU_MAX_ATOMS_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_MAX_ATOMS"
GPU_MAX_MOLECULES_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_MAX_MOLECULES"
GPU_DIRECT_TIMEOUT_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_DIRECT_TIMEOUT_S"
GPU_PACKMOL_TIMEOUT_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_PACKMOL_TIMEOUT_S"
GPU_INTERCHANGE_TIMEOUT_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_INTERCHANGE_TIMEOUT_S"
GPU_CUDA_TIMEOUT_ENV_VAR = "POLYZYMD_CONJUGATION_GPU_SOLVATION_CUDA_TIMEOUT_S"
DEFAULT_GPU_PADDING_NM = 0.25
DEFAULT_GPU_MINIMIZATION_ITERS = 500
WATER_NUMBER_DENSITY_NM3 = 33.4


@dataclass(frozen=True)
class SolvationSmokeLimits:
    """Safety limits for the opt-in GPU solvation smoke."""

    max_solute_span_nm: float
    max_box_edge_nm: float
    max_waters: int
    max_atoms: int
    max_molecules: int


@dataclass(frozen=True)
class SolvationBoxEstimate:
    """Pre-PACKMOL estimate used to fail fast on oversized smokes."""

    solute_span_nm: tuple[float, float, float]
    padded_lengths_nm: tuple[float, float, float]
    volume_nm3: float
    estimated_waters: int


@pytest.mark.slow
@pytest.mark.conjugation_stack
def test_opt_in_cuda_required_for_conjugation_solvation_full_build(tmp_path: Path):
    """Require CUDA and prove a solvated system can create a finite CUDA state.

    This expensive test is intentionally opt-in and must not fall back to CPU.
    The linked conjugate input is generated by default and must complete the
    direct link, restrained vacuum minimization, and short vacuum MD before the
    relaxed conformer is solvated through the OpenFF/PACKMOL/Interchange path.
    """
    openmm, openmm_unit, platform = _require_gpu_solvation_stack_or_skip()
    artifact_dir = tmp_path / "gpu-solvation"
    artifact_dir.mkdir(parents=True, exist_ok=True)
    limits = _solvation_smoke_limits_from_env()
    padding_nm = _float_env(GPU_PADDING_ENV_VAR, default=DEFAULT_GPU_PADDING_NM)
    print(
        "[conjugation-gpu-smoke] Limits: "
        f"padding={padding_nm:.3f} nm, max_span={limits.max_solute_span_nm:.3f} nm, "
        f"max_box_edge={limits.max_box_edge_nm:.3f} nm, max_waters={limits.max_waters}, "
        f"max_atoms={limits.max_atoms}, max_molecules={limits.max_molecules}"
    )

    with _timed_stage(
        "direct artifact generation",
        timeout_s=_timeout_seconds_env(GPU_DIRECT_TIMEOUT_ENV_VAR, default=300.0),
    ):
        direct_result = _direct_artifact_from_env_or_generate(artifact_dir)
    assert direct_result.linked_pdb_path.exists()
    assert direct_result.linked_bond.conect_present is True
    assert direct_result.topology is not None
    assert direct_result.charge_template is not None
    expected_restrained_atom_count = len(_all_heavy_atom_indices(direct_result.linked_pdb_path))
    protein_heavy_atom_count = len(_protein_heavy_atom_indices(direct_result.linked_pdb_path))
    assert expected_restrained_atom_count > protein_heavy_atom_count

    from openff.interchange.interop.openmm._positions import to_openmm_positions

    from polyzymd.builders.conjugation.pablo.parameterization import (
        create_interchange_from_openff_topology,
        set_topology_positions_from_pdb,
    )
    from polyzymd.builders.conjugation._relaxation import VacuumSmokeSettings, run_restrained_vacuum_smoke
    from polyzymd.builders.solvent import SolventBuilder, SolventComposition
    from polyzymd.data.solvent_molecules import get_solvent_molecule

    with _timed_stage("vacuum parameterization"):
        vacuum_parameterization = create_interchange_from_openff_topology(
            direct_result.topology,
            charge_from_molecules=(direct_result.charge_template,),
            success_diagnostic="Direct linked conjugate was parameterized before vacuum relaxation",
            failure_subject="direct linked conjugate topology",
        )
    assert vacuum_parameterization.interchange is not None

    with _timed_stage("restrained vacuum EM and MD"):
        vacuum_result = run_restrained_vacuum_smoke(
            vacuum_parameterization.interchange,
            artifact_dir / "vacuum-relaxation",
            protein_heavy_atom_indices=None,
            settings=VacuumSmokeSettings(
                minimization_max_iterations=_int_env(
                    GPU_MINIMIZATION_ITERS_ENV_VAR,
                    default=DEFAULT_GPU_MINIMIZATION_ITERS,
                ),
                nvt_steps=_positive_int_env(GPU_NVT_STEPS_ENV_VAR, default=2),
                platform_name="CUDA",
            ),
        )
    assert vacuum_result.success
    assert vacuum_result.equilibrated_pdb_path is not None
    assert vacuum_result.equilibrated_pdb_path.exists()
    assert vacuum_result.nvt_steps > 0, "Restrained vacuum MD must run before solvation"
    assert vacuum_result.restrained_atom_count == expected_restrained_atom_count

    with _timed_stage("relaxed position transfer"):
        relaxed_topology = set_topology_positions_from_pdb(
            direct_result.topology,
            vacuum_result.equilibrated_pdb_path,
        )

    with _timed_stage("solvation box and count setup"):
        estimate = _estimate_solvation_box(relaxed_topology, padding_nm=padding_nm)
        _print_solvation_estimate(estimate)
        _guard_solvation_box_estimate(estimate, limits)

    solvent_builder = SolventBuilder()
    with _timed_stage(
        "PACKMOL solvation",
        timeout_s=_timeout_seconds_env(GPU_PACKMOL_TIMEOUT_ENV_VAR, default=180.0),
    ):
        solvated_topology = solvent_builder.solvate(
            relaxed_topology,
            composition=SolventComposition(
                water_model="tip3p",
                nacl_concentration=0.0,
                neutralize=False,
            ),
            padding=padding_nm,
            box_shape="cube",
            tolerance=2.0,
        )
    _print_solvated_topology_summary(solvated_topology, solvent_builder)
    _guard_solvated_topology_size(solvated_topology, solvent_builder, limits)
    solvated_pdb = artifact_dir / "solvated_system.pdb"
    solvated_topology.to_file(str(solvated_pdb), keep_ids=True)

    with _timed_stage(
        "solvated Interchange creation",
        timeout_s=_timeout_seconds_env(GPU_INTERCHANGE_TIMEOUT_ENV_VAR, default=300.0),
    ):
        solvated_parameterization = create_interchange_from_openff_topology(
            solvated_topology,
            charge_from_molecules=(direct_result.charge_template, get_solvent_molecule("tip3p")),
            success_diagnostic="Relaxed direct conjugate was solvated and parameterized",
            failure_subject="solvated direct conjugate topology",
        )
    assert solvated_parameterization.interchange is not None

    with _timed_stage(
        "OpenMM CUDA system/context/energy/force evaluation",
        timeout_s=_timeout_seconds_env(GPU_CUDA_TIMEOUT_ENV_VAR, default=120.0),
    ):
        system = solvated_parameterization.interchange.to_openmm_system()
        system_xml = artifact_dir / "system.xml"
        system_xml.write_text(openmm.XmlSerializer.serialize(system), encoding="utf-8")
        positions = to_openmm_positions(
            solvated_parameterization.interchange,
            include_virtual_sites=True,
        )

        integrator = openmm.VerletIntegrator(0.001 * openmm_unit.picoseconds)
        context = openmm.Context(system, integrator, platform, {"CudaPrecision": "mixed"})
        context.setPositions(positions)
        state = context.getState(getEnergy=True, getForces=True)
        energy = state.getPotentialEnergy().value_in_unit(openmm_unit.kilojoule_per_mole)
        forces = state.getForces(asNumpy=True).value_in_unit(
            openmm_unit.kilojoule_per_mole / openmm_unit.nanometer
        )
        context_platform = context.getPlatform().getName()
        del context
        del integrator

    assert context_platform == "CUDA"
    assert solvated_pdb.exists()
    assert system_xml.exists()
    assert math.isfinite(float(energy))
    assert np.all(np.isfinite(forces))


def test_gpu_solvation_smoke_source_avoids_openmm_modeller_solvation():
    """The GPU solvation smoke should stay on the OpenFF/PACKMOL route."""
    source = Path(__file__).read_text(encoding="utf-8")
    forbidden_tokens = (
        "".join(("amber14", "-", "all.xml")),
        "".join(("add", "Solvent")),
        "".join(("Mod", "eller")),
    )
    for token in forbidden_tokens:
        assert token not in source


def test_gpu_solvation_smoke_source_uses_all_heavy_vacuum_restraints():
    """The GPU path should not pass a protein-only restraint selection."""
    source = Path(__file__).read_text(encoding="utf-8")
    protein_only_call = "protein_heavy_atom_indices=" + "_protein_heavy_atom_indices"

    assert "protein_heavy_atom_indices=None" in source
    assert protein_only_call not in source


def test_gpu_solvation_nvt_steps_env_rejects_zero(monkeypatch: pytest.MonkeyPatch):
    """The GPU solvation smoke must run short vacuum MD before solvation."""
    monkeypatch.setenv(GPU_NVT_STEPS_ENV_VAR, "0")

    with pytest.raises(ValueError, match=f"{GPU_NVT_STEPS_ENV_VAR} must be positive"):
        _positive_int_env(GPU_NVT_STEPS_ENV_VAR, default=2)


def test_gpu_solvation_minimization_default_is_nontrivial(monkeypatch: pytest.MonkeyPatch):
    """The GPU solvation smoke should not rely on a near-zero minimization fallback."""
    monkeypatch.delenv(GPU_MINIMIZATION_ITERS_ENV_VAR, raising=False)

    fallback = _int_env(
        GPU_MINIMIZATION_ITERS_ENV_VAR,
        default=DEFAULT_GPU_MINIMIZATION_ITERS,
    )

    assert fallback == DEFAULT_GPU_MINIMIZATION_ITERS
    assert fallback >= 100


def test_gpu_solvation_padding_env_rejects_zero(monkeypatch: pytest.MonkeyPatch):
    """The GPU solvation smoke requires positive padding."""
    monkeypatch.setenv(GPU_PADDING_ENV_VAR, "0")

    with pytest.raises(ValueError, match=f"{GPU_PADDING_ENV_VAR} must be positive"):
        _float_env(GPU_PADDING_ENV_VAR, default=DEFAULT_GPU_PADDING_NM)


def test_gpu_solvation_box_guard_rejects_oversized_estimate():
    """The pre-PACKMOL guard should fail fast on oversized solvent boxes."""
    limits = SolvationSmokeLimits(
        max_solute_span_nm=6.0,
        max_box_edge_nm=6.5,
        max_waters=5_000,
        max_atoms=25_000,
        max_molecules=7_000,
    )
    estimate = SolvationBoxEstimate(
        solute_span_nm=(5.0, 5.0, 7.0),
        padded_lengths_nm=(5.5, 5.5, 7.5),
        volume_nm3=226.875,
        estimated_waters=7_578,
    )

    with pytest.raises(
        pytest.fail.Exception,
        match="Pre-PACKMOL solvation estimate exceeds smoke limits",
    ):
        _guard_solvation_box_estimate(estimate, limits)


def test_gpu_solvation_topology_guard_rejects_many_atoms():
    """The post-PACKMOL guard should reject unexpectedly large topologies."""
    limits = SolvationSmokeLimits(
        max_solute_span_nm=6.0,
        max_box_edge_nm=6.5,
        max_waters=5_000,
        max_atoms=25_000,
        max_molecules=7_000,
    )

    class TopologyDouble:
        """Small topology-like object for size guard tests."""

        n_atoms = 25_001
        n_molecules = 6_000

    with pytest.raises(pytest.fail.Exception, match="Solvated topology exceeds smoke limits"):
        _guard_solvated_topology_size(TopologyDouble(), solvent_builder=None, limits=limits)


def _require_gpu_solvation_stack_or_skip():
    """Return OpenMM modules and a validated CUDA platform or skip."""
    if os.environ.get(GPU_ENV_VAR) != "1":
        pytest.skip(f"Set {GPU_ENV_VAR}=1 to run the CUDA solvation smoke")
    if shutil.which("packmol") is None:
        pytest.skip("Packmol binary is not available on PATH")

    pytest.importorskip("polymerist", exc_type=ImportError)
    pytest.importorskip("openff.toolkit")
    pytest.importorskip("openff.interchange")
    pytest.importorskip("rdkit")

    openmm = pytest.importorskip("openmm")
    from openmm import unit as openmm_unit

    try:
        platform = openmm.Platform.getPlatformByName("CUDA")
    except Exception as exc:  # noqa: BLE001 - OpenMM platform lookup varies by installation
        pytest.skip(f"CUDA platform is required and no CPU fallback is allowed: {exc}")

    probe_system = openmm.System()
    probe_system.addParticle(39.9)
    probe_integrator = openmm.VerletIntegrator(0.001 * openmm_unit.picoseconds)
    try:
        probe_context = openmm.Context(probe_system, probe_integrator, platform)
        probe_context.setPositions([[0.0, 0.0, 0.0]] * openmm_unit.nanometer)
        probe_context.getState(getEnergy=True)
    except Exception as exc:  # noqa: BLE001 - CUDA resource failures vary by cluster state
        pytest.skip(f"CUDA platform is registered but unusable; no CPU fallback is allowed: {exc}")
    finally:
        if "probe_context" in locals():
            del probe_context
        del probe_integrator

    return openmm, openmm_unit, platform


def _direct_artifact_from_env_or_generate(artifact_dir: Path):
    """Return or generate the direct linked conjugate artifact for the GPU smoke."""
    value = os.environ.get("POLYZYMD_CONJUGATION_LINKED_PDB")
    if value:
        pytest.fail(
            "POLYZYMD_CONJUGATION_LINKED_PDB is no longer accepted for the GPU solvation smoke. "
            "The test must generate a direct artifact with an OpenFF topology and charge template "
            "so it can run vacuum relaxation before solvation."
        )

    from tests.test_conjugation_integrated_direct_smoke import build_direct_smoke_artifact

    return build_direct_smoke_artifact(artifact_dir / "direct-input")


def _protein_heavy_atom_indices(pdb_path: Path) -> tuple[int, ...]:
    """Return zero-based chain-A non-hydrogen atom indices from a PDB artifact."""
    indices: list[int] = []
    for atom in _heavy_atom_records(pdb_path):
        if atom.atom_index is None:
            continue
        if atom.chain_id == "A":
            indices.append(atom.atom_index)
    if not indices:
        pytest.fail(f"No chain-A heavy atoms were found for restraints in {pdb_path}")
    return tuple(indices)


def _all_heavy_atom_indices(pdb_path: Path) -> tuple[int, ...]:
    """Return zero-based non-hydrogen atom indices from a PDB artifact."""
    indices = tuple(
        atom.atom_index for atom in _heavy_atom_records(pdb_path) if atom.atom_index is not None
    )
    if not indices:
        pytest.fail(f"No heavy atoms were found for restraints in {pdb_path}")
    return indices


def _heavy_atom_records(pdb_path: Path) -> Iterator[Any]:
    """Yield non-hydrogen PDB atom records from a linked conjugate artifact."""
    from polyzymd.builders.conjugation._linkage import parse_pdb_atom_records

    for atom in parse_pdb_atom_records(pdb_path):
        element = (atom.element or "").upper()
        if element != "H" and not atom.atom_name.upper().startswith("H"):
            yield atom


@contextmanager
def _timed_stage(stage_name: str, *, timeout_s: float | None = None) -> Iterator[None]:
    """Print wall-time diagnostics and optionally fail on a stage timeout.

    Parameters
    ----------
    stage_name : str
        Human-readable stage name shown in pytest ``-s`` output.
    timeout_s : float or None, optional
        Wall-time timeout in seconds. ``None`` disables the alarm.
    """
    start = time.perf_counter()
    timeout_label = "none" if timeout_s is None else f"{timeout_s:.1f} s"
    print(f"[conjugation-gpu-smoke] START {stage_name} (timeout={timeout_label})")
    old_handler = None
    old_timer = None
    timer_enabled = timeout_s is not None and hasattr(signal, "SIGALRM")

    if timer_enabled:
        old_handler = signal.getsignal(signal.SIGALRM)

        def _raise_timeout(signum: int, frame: object) -> None:
            del signum, frame
            raise TimeoutError(
                f"Stage '{stage_name}' exceeded {timeout_s:.1f} seconds. "
                "Increase the corresponding POLYZYMD_CONJUGATION_GPU_SOLVATION_*_TIMEOUT_S "
                "environment variable only after checking the stage diagnostics."
            )

        signal.signal(signal.SIGALRM, _raise_timeout)
        old_timer = signal.setitimer(signal.ITIMER_REAL, float(timeout_s))

    try:
        yield
    except TimeoutError as exc:
        elapsed = time.perf_counter() - start
        print(f"[conjugation-gpu-smoke] TIMEOUT {stage_name} after {elapsed:.2f} s: {exc}")
        pytest.fail(str(exc))
    finally:
        if timer_enabled:
            signal.setitimer(signal.ITIMER_REAL, 0.0)
            if old_timer is not None and old_timer[0] > 0.0:
                remaining = max(old_timer[0] - (time.perf_counter() - start), 0.0)
                signal.setitimer(signal.ITIMER_REAL, remaining, old_timer[1])
            signal.signal(signal.SIGALRM, old_handler)
        elapsed = time.perf_counter() - start
        print(f"[conjugation-gpu-smoke] END {stage_name} ({elapsed:.2f} s)")


def _solvation_smoke_limits_from_env() -> SolvationSmokeLimits:
    """Read smoke-size guard limits from environment variables."""
    return SolvationSmokeLimits(
        max_solute_span_nm=_float_env(GPU_MAX_SOLUTE_SPAN_ENV_VAR, default=7.0),
        max_box_edge_nm=_float_env(GPU_MAX_BOX_EDGE_ENV_VAR, default=8.0),
        max_waters=_positive_int_env(GPU_MAX_WATERS_ENV_VAR, default=8_000),
        max_atoms=_positive_int_env(GPU_MAX_ATOMS_ENV_VAR, default=35_000),
        max_molecules=_positive_int_env(GPU_MAX_MOLECULES_ENV_VAR, default=10_000),
    )


def _estimate_solvation_box(topology: object, *, padding_nm: float) -> SolvationBoxEstimate:
    """Estimate padded cube dimensions and an upper-bound water count.

    Parameters
    ----------
    topology : object
        OpenFF topology-like object with finite coordinates.
    padding_nm : float
        Solvent padding in nanometers.

    Returns
    -------
    SolvationBoxEstimate
        Coordinate span, padded box lengths, volume, and estimated water count.
    """
    positions_nm = _topology_positions_nm(topology)
    solute_span = np.ptp(positions_nm, axis=0)
    padded_lengths = solute_span + 2.0 * padding_nm
    volume_nm3 = float(np.prod(padded_lengths))
    estimated_waters = int(math.ceil(volume_nm3 * WATER_NUMBER_DENSITY_NM3))
    return SolvationBoxEstimate(
        solute_span_nm=tuple(float(value) for value in solute_span),
        padded_lengths_nm=tuple(float(value) for value in padded_lengths),
        volume_nm3=volume_nm3,
        estimated_waters=estimated_waters,
    )


def _topology_positions_nm(topology: object) -> np.ndarray:
    """Return topology coordinates as a finite ``(n_atoms, 3)`` nanometer array."""
    get_positions = getattr(topology, "get_positions", None)
    positions = get_positions() if callable(get_positions) else None
    if positions is None:
        positions = _stack_molecule_conformers_nm(topology)
    elif hasattr(positions, "m_as"):
        positions = positions.m_as("nanometer")
    array = np.asarray(positions, dtype=float)
    if array.ndim != 2 or array.shape[1] != 3:
        raise ValueError(f"Topology positions must have shape (n_atoms, 3), got {array.shape}")
    if array.shape[0] == 0:
        raise ValueError("Topology positions are empty; cannot estimate solvation box")
    if not bool(np.all(np.isfinite(array))):
        raise ValueError("Topology positions contain non-finite coordinates")
    return array


def _stack_molecule_conformers_nm(topology: object) -> np.ndarray:
    """Stack first conformers from topology molecules when direct positions are absent."""
    arrays: list[np.ndarray] = []
    for molecule in getattr(topology, "molecules", ()):  # pragma: no branch - test doubles vary
        conformers = getattr(molecule, "conformers", ())
        if not conformers:
            continue
        conformer = conformers[0]
        if hasattr(conformer, "m_as"):
            arrays.append(np.asarray(conformer.m_as("nanometer"), dtype=float))
        else:
            arrays.append(np.asarray(conformer, dtype=float))
    if not arrays:
        raise ValueError("Topology has no positions or molecule conformers for box estimation")
    return np.vstack(arrays)


def _print_solvation_estimate(estimate: SolvationBoxEstimate) -> None:
    """Print the pre-PACKMOL solvation estimate."""
    print(
        "[conjugation-gpu-smoke] Pre-PACKMOL estimate: "
        f"span_nm={_format_triplet(estimate.solute_span_nm)}, "
        f"padded_lengths_nm={_format_triplet(estimate.padded_lengths_nm)}, "
        f"volume={estimate.volume_nm3:.2f} nm^3, "
        f"estimated_waters<={estimate.estimated_waters}"
    )


def _guard_solvation_box_estimate(
    estimate: SolvationBoxEstimate,
    limits: SolvationSmokeLimits,
) -> None:
    """Fail before PACKMOL when the estimated smoke system is too large."""
    failures: list[str] = []
    max_span = max(estimate.solute_span_nm)
    max_box_edge = max(estimate.padded_lengths_nm)
    if max_span > limits.max_solute_span_nm:
        failures.append(f"solute span {max_span:.3f} nm > {limits.max_solute_span_nm:.3f} nm")
    if max_box_edge > limits.max_box_edge_nm:
        failures.append(f"box edge {max_box_edge:.3f} nm > {limits.max_box_edge_nm:.3f} nm")
    if estimate.estimated_waters > limits.max_waters:
        failures.append(f"estimated waters {estimate.estimated_waters} > {limits.max_waters}")
    if failures:
        pytest.fail(
            "Pre-PACKMOL solvation estimate exceeds smoke limits: "
            + "; ".join(failures)
            + ". Reduce the fixture size/padding or override the guard env vars if intentional."
        )


def _print_solvated_topology_summary(topology: object, solvent_builder: object) -> None:
    """Print immediate post-PACKMOL topology and solvent counts."""
    counts = getattr(solvent_builder, "solvation_counts", None)
    water = "unknown" if counts is None else str(counts.water)
    na = "unknown" if counts is None else str(counts.na)
    cl = "unknown" if counts is None else str(counts.cl)
    print(
        "[conjugation-gpu-smoke] Post-PACKMOL topology: "
        f"atoms={int(topology.n_atoms)}, "
        f"molecules={int(topology.n_molecules)}, "
        f"water={water}, Na={na}, Cl={cl}"
    )


def _guard_solvated_topology_size(
    topology: object,
    solvent_builder: object | None,
    limits: SolvationSmokeLimits,
) -> None:
    """Fail immediately after PACKMOL when topology size exceeds smoke limits."""
    failures: list[str] = []
    atom_count = int(topology.n_atoms)
    molecule_count = int(topology.n_molecules)
    counts = None if solvent_builder is None else getattr(solvent_builder, "solvation_counts", None)
    if atom_count > limits.max_atoms:
        failures.append(f"atoms {atom_count} > {limits.max_atoms}")
    if molecule_count > limits.max_molecules:
        failures.append(f"molecules {molecule_count} > {limits.max_molecules}")
    if counts is not None and counts.water > limits.max_waters:
        failures.append(f"waters {counts.water} > {limits.max_waters}")
    if failures:
        pytest.fail(
            "Solvated topology exceeds smoke limits: "
            + "; ".join(failures)
            + ". This would make Interchange or CUDA diagnostics too slow for the smoke."
        )


def _format_triplet(values: tuple[float, float, float]) -> str:
    """Format a numeric triplet for compact stage diagnostics."""
    return "(" + ", ".join(f"{value:.3f}" for value in values) + ")"


def _int_env(name: str, *, default: int) -> int:
    """Read a non-negative integer environment override."""
    value = os.environ.get(name)
    if value is None or value == "":
        return default
    parsed = int(value)
    if parsed < 0:
        raise ValueError(f"{name} must be non-negative, got {parsed}")
    return parsed


def _positive_int_env(name: str, *, default: int) -> int:
    """Read a positive integer environment override."""
    value = os.environ.get(name)
    if value is None or value == "":
        return default
    parsed = int(value)
    if parsed <= 0:
        raise ValueError(f"{name} must be positive, got {parsed}")
    return parsed


def _float_env(name: str, *, default: float) -> float:
    """Read a positive float environment override."""
    value = os.environ.get(name)
    if value is None or value == "":
        return default
    parsed = float(value)
    if parsed <= 0.0:
        raise ValueError(f"{name} must be positive, got {parsed}")
    return parsed


def _timeout_seconds_env(name: str, *, default: float) -> float | None:
    """Read a timeout override, returning ``None`` when disabled with zero."""
    value = os.environ.get(name)
    if value is None or value == "":
        parsed = default
    else:
        parsed = float(value)
    if parsed < 0.0:
        raise ValueError(f"{name} must be non-negative, got {parsed}")
    if parsed == 0.0:
        return None
    return parsed
