"""GROMACS-specific SLURM job script generation."""

from __future__ import annotations

import logging
import os
from pathlib import Path

from polyzymd.core.branding import FULL_CREDIT_LINE
from polyzymd.workflow.slurm import SlurmConfig, _discover_manifest_path, _validate_script_value

LOGGER = logging.getLogger(__name__)


class GromacsSlurmScriptGenerator:
    """Generate self-resubmitting SLURM scripts for GROMACS simulations.

    The generated script handles the complete lifecycle:

    - Activates the requested pixi environment
    - Optionally loads an HPC module (for example ``module load gromacs/2024``)
    - Resolves the GROMACS binary and runs EM plus staged equilibration
    - Runs production with ``-maxh`` and checkpoint restart via ``-cpi``
    - Updates ``progress.json`` with ``polyzymd _update-gromacs-progress``
    - Resubmits itself with ``sbatch`` until production is complete
    """

    MAXH_SAFETY_FACTOR = 0.90

    JOB_TEMPLATE = """#!/bin/bash
#SBATCH --partition={partition}
#SBATCH --job-name={job_name}
#SBATCH --output={output_file}
{qos_line}
{nodes_line}
{cpus_line}
{mem_line}
#SBATCH --time={time_limit}
{gpu_line}
{mail_line}
{account_line}
{exclude_line}
#SBATCH --no-requeue

# =============================================================================
# PolyzyMD GROMACS Self-Resubmitting Simulation Job
# {FULL_CREDIT_LINE}
# Generated by polyzymd — do not edit manually
# =============================================================================

# Activate pixi environment
eval "$(pixi shell-hook -e {pixi_env} --manifest-path {manifest_path})"

{module_load_line}

# Enable strict error handling after environment setup
set -e

# Resolve this script's path for self-resubmission
THIS_SCRIPT="${{SLURM_JOB_SCRIPT:-$(realpath "$0")}}"

# Configuration
CONFIG_PATH="{config_path}"
REPLICATE={replicate}
WORKING_DIR="{working_dir}"
GMX="{gmx_binary}"
PREFIX="{system_prefix}"
MAXH={maxh_hours}

# Ensure working directory exists
mkdir -p "$WORKING_DIR"
cd "$WORKING_DIR"

echo "=================================================="
echo "PolyzyMD GROMACS self-resubmitting job"
echo "{FULL_CREDIT_LINE}"
echo "Config:    $CONFIG_PATH"
echo "Replicate: $REPLICATE"
echo "Work dir:  $WORKING_DIR"
echo "GMX:       $GMX"
echo "Pixi env:  {pixi_env}"
echo "Job ID:    ${{SLURM_JOB_ID:-local}}"
echo "Max hours: $MAXH"
echo "Timestamp: $(date)"
echo "=================================================="

# =========================================================================
# Step 1: Energy minimization (skip if already done)
# =========================================================================
{energy_minimization_block}

# =========================================================================
# Step 2: Equilibration (skip completed stages)
# =========================================================================
{equilibration_block}

# =========================================================================
# Step 3: Production MD with checkpoint restart
# =========================================================================
echo "=== Production MD ==="

# Create TPR if needed
if [ ! -f prod.tpr ]; then
    if [ -f ${{LAST_EQ}}.cpt ]; then
        $GMX grompp -f prod.mdp -c ${{LAST_EQ}}.gro -r em.gro -t ${{LAST_EQ}}.cpt \\
            -p ${{PREFIX}}.top -o prod.tpr {grompp_flags}
    else
        $GMX grompp -f prod.mdp -c ${{LAST_EQ}}.gro -r em.gro -p ${{PREFIX}}.top -o prod.tpr {grompp_flags}
    fi
fi

# Run production: -cpi for checkpoint restart, -append to extend existing files
# -maxh limits wall time so we can cleanly resubmit
MDRUN_FLAGS="{mdrun_flags}"
if [ -f state.cpt ]; then
    echo "Resuming from checkpoint: state.cpt"
    $GMX mdrun -deffnm prod -cpi state.cpt -cpo state.cpt -append -maxh $MAXH $MDRUN_FLAGS -v
else
    echo "Starting fresh production run"
    $GMX mdrun -deffnm prod -cpo state.cpt -maxh $MAXH $MDRUN_FLAGS -v
fi

MDRUN_RC=$?

# =========================================================================
# Step 4: Update progress tracking
# =========================================================================
set +e
polyzymd _update-gromacs-progress \\
    --working-dir "$WORKING_DIR" \\
    --config-path "$CONFIG_PATH" \\
    --replicate "$REPLICATE"
PROGRESS_RC=$?
set -e

if [ $PROGRESS_RC -ne 0 ]; then
    echo "WARNING: Progress update failed (exit code $PROGRESS_RC)"
fi

# =========================================================================
# Step 5: Check completion and resubmit if needed
# =========================================================================
if [ -f prod.log ]; then
    if grep -q "Finished mdrun" prod.log; then
        echo "Production simulation complete — no resubmission needed."

        # Run post-processing (trajectory centering)
        echo "=== Post-processing ==="
        echo "System" | $GMX trjconv -s prod.tpr -f prod.xtc -o prod_nojump.xtc -pbc nojump 2>/dev/null || true
        echo -e "Protein\\nSystem" | $GMX trjconv -s prod.tpr -f prod_nojump.xtc -o prod_centered.xtc -center -pbc mol -ur compact 2>/dev/null || true

        # Final progress update marking completion
        polyzymd _update-gromacs-progress \\
            --working-dir "$WORKING_DIR" \\
            --config-path "$CONFIG_PATH" \\
            --replicate "$REPLICATE" \\
            --mark-complete || true

        echo "All done."
        exit 0
    fi
fi

echo "Production incomplete (wall-time limit reached) — resubmitting..."
sbatch "$THIS_SCRIPT"
SUBMIT_RC=$?

if [ $SUBMIT_RC -eq 0 ]; then
    echo "Resubmitted successfully."
else
    echo "WARNING: sbatch resubmission failed (exit code $SUBMIT_RC)"
    echo "You can manually resume with: sbatch $THIS_SCRIPT"
    exit 1
fi

exit 0
"""

    def __init__(
        self,
        slurm_config: SlurmConfig,
        pixi_env: str = "cuda-12-4",
        gmx_binary: str = "gmx",
        grompp_flags: str = "-maxwarn 1",
        mdrun_flags: str = "",
        module_load: str | None = None,
    ) -> None:
        """Initialize the GROMACS SLURM script generator.

        Parameters
        ----------
        slurm_config : SlurmConfig
            Scheduler resource configuration.
        pixi_env : str, optional
            Pixi environment name used for job execution.
        gmx_binary : str, optional
            GROMACS executable path or command name.
        grompp_flags : str, optional
            Extra flags appended to ``gmx grompp`` invocations.
        mdrun_flags : str, optional
            Extra flags appended to ``gmx mdrun`` invocations.
        module_load : str | None, optional
            Optional module command executed before simulation commands.
        """
        self._config = slurm_config
        self._pixi_env = pixi_env
        self._gmx_binary = gmx_binary
        self._grompp_flags = grompp_flags
        self._mdrun_flags = mdrun_flags
        self._module_load = module_load

    def _gpu_line(self) -> str:
        """Return the GPU SBATCH directive for the configured cluster style."""
        if self._config.gpus == 0:
            return ""
        if self._config.gpu_directive_style == "gpus" and self._config.gpu_type:
            return f"#SBATCH --gpus={self._config.gpu_type}:{self._config.gpus}"
        return f"#SBATCH --gres=gpu:{self._config.gpus}"

    def _nodes_line(self) -> str:
        """Return nodes and tasks directives for the configured cluster style."""
        if self._config.gpu_directive_style == "gpus" and self._config.gpus > 0:
            return f"#SBATCH -N {self._config.nodes}"
        return f"#SBATCH --nodes={self._config.nodes}\n#SBATCH --ntasks={self._config.ntasks}"

    def _cpus_line(self) -> str:
        """Return CPUs-per-task SBATCH directive when greater than one."""
        if self._config.cpus_per_task > 1:
            return f"#SBATCH --cpus-per-task={self._config.cpus_per_task}"
        return ""

    def _qos_line(self) -> str:
        """Return the optional QoS SBATCH directive."""
        return f"#SBATCH --qos={self._config.qos}" if self._config.qos else ""

    def _mem_line(self) -> str:
        """Return the optional memory SBATCH directive."""
        return f"#SBATCH --mem={self._config.memory}" if self._config.memory else ""

    def _account_line(self) -> str:
        """Return the optional account SBATCH directive."""
        return f"#SBATCH --account={self._config.account}" if self._config.account else ""

    def _mail_line(self) -> str:
        """Return optional SLURM email directives."""
        if self._config.email:
            return f"#SBATCH --mail-type=FAIL\n#SBATCH --mail-user={self._config.email}"
        return ""

    def _exclude_line(self) -> str:
        """Return optional node exclusion SBATCH directive."""
        return f"#SBATCH --exclude={self._config.exclude}" if self._config.exclude else ""

    def generate_job_script(
        self,
        config_path: str,
        replicate: int,
        working_dir: str,
        system_prefix: str,
        equilibration_mdps: list[str],
        job_name: str | None = None,
        output_file: str | None = None,
        use_soft_em: bool = True,
    ) -> str:
        """Generate a self-resubmitting GROMACS SLURM script.

        Parameters
        ----------
        config_path : str
            Path to the simulation YAML config.
        replicate : int
            Replicate index.
        working_dir : str
            Directory containing exported GROMACS files and outputs.
        system_prefix : str
            Prefix used by exported ``.gro`` and ``.top`` files.
        equilibration_mdps : list[str]
            Ordered equilibration stage MDP filenames.
        job_name : str | None, optional
            Custom scheduler job name.
        output_file : str | None, optional
            Custom SLURM log path pattern.
        use_soft_em : bool, optional
            Whether to use two-stage minimization with ``em_soft.mdp``.

        Returns
        -------
        str
            Full script content.
        """
        if job_name is None:
            job_name = f"pzmd_gmx_r{replicate}"
        if output_file is None:
            output_file = f"slurm_logs/{job_name}.%j.out"

        wall_hours = self._parse_wall_time_hours(self._config.time_limit)
        maxh_hours = wall_hours * self.MAXH_SAFETY_FACTOR
        energy_minimization_block = self._generate_energy_minimization_block(use_soft_em)
        equilibration_block = self._generate_equilibration_block(equilibration_mdps)
        manifest_path = _discover_manifest_path()
        module_load_line = self._module_load if self._module_load else ""

        _validate_script_value(self._config.partition, "partition")
        _validate_script_value(job_name, "job_name")
        _validate_script_value(output_file, "output_file")
        _validate_script_value(self._config.time_limit, "time_limit")
        _validate_script_value(self._pixi_env, "pixi_env")
        _validate_script_value(str(manifest_path), "manifest_path")
        _validate_script_value(str(config_path), "config_path")
        _validate_script_value(str(working_dir), "working_dir")
        _validate_script_value(self._gmx_binary, "gmx_binary")
        _validate_script_value(system_prefix, "system_prefix")
        _validate_script_value(self._grompp_flags, "grompp_flags")
        _validate_script_value(self._mdrun_flags, "mdrun_flags")
        if module_load_line:
            _validate_script_value(module_load_line, "module_load")
        if self._config.qos:
            _validate_script_value(self._config.qos, "qos")
        if self._config.memory:
            _validate_script_value(self._config.memory, "memory")
        if self._config.account:
            _validate_script_value(self._config.account, "account")
        if self._config.email:
            _validate_script_value(self._config.email, "email")
        if self._config.exclude:
            _validate_script_value(self._config.exclude, "exclude")
        if self._config.gpu_type:
            _validate_script_value(self._config.gpu_type, "gpu_type")
        for mdp_name in equilibration_mdps:
            _validate_script_value(mdp_name, "equilibration_mdp")

        return self.JOB_TEMPLATE.format(
            partition=self._config.partition,
            job_name=job_name,
            output_file=output_file,
            qos_line=self._qos_line(),
            nodes_line=self._nodes_line(),
            cpus_line=self._cpus_line(),
            mem_line=self._mem_line(),
            time_limit=self._config.time_limit,
            gpu_line=self._gpu_line(),
            mail_line=self._mail_line(),
            account_line=self._account_line(),
            exclude_line=self._exclude_line(),
            pixi_env=self._pixi_env,
            manifest_path=manifest_path,
            config_path=config_path,
            replicate=replicate,
            working_dir=working_dir,
            gmx_binary=self._gmx_binary,
            system_prefix=system_prefix,
            maxh_hours=f"{maxh_hours:.2f}",
            grompp_flags=self._grompp_flags,
            mdrun_flags=self._mdrun_flags,
            energy_minimization_block=energy_minimization_block,
            equilibration_block=equilibration_block,
            module_load_line=module_load_line,
            FULL_CREDIT_LINE=FULL_CREDIT_LINE,
        )

    def _generate_energy_minimization_block(self, use_soft_em: bool) -> str:
        """Generate EM bash block with optional gentle first stage.

        Parameters
        ----------
        use_soft_em : bool
            Whether to run gentle stage-1 minimization before standard EM.

        Returns
        -------
        str
            Rendered bash block.
        """
        if use_soft_em:
            lines = [
                "# Stage 1: Gentle energy minimization (handles clashing atoms)",
                "if [ ! -f em_soft.gro ]; then",
                '    echo "=== Energy Minimization Stage 1 (gentle) ==="',
                "    $GMX grompp -f em_soft.mdp -c ${{PREFIX}}.gro -r ${{PREFIX}}.gro -p ${{PREFIX}}.top -o em_soft.tpr {grompp_flags}",
                "    $GMX mdrun -deffnm em_soft -v",
                "    if [ ! -f em_soft.gro ]; then",
                '        echo "FATAL: Gentle energy minimization failed — em_soft.gro not produced"',
                "        exit 1",
                "    fi",
                '    echo "Gentle energy minimization complete."',
                "else",
                '    echo "Skipping gentle energy minimization (em_soft.gro exists)."',
                "fi",
                "",
                "# Stage 2: Standard energy minimization",
                "if [ ! -f em.gro ]; then",
                '    echo "=== Energy Minimization Stage 2 (standard) ==="',
                "    $GMX grompp -f em.mdp -c em_soft.gro -r em_soft.gro -p ${{PREFIX}}.top -o em.tpr {grompp_flags}",
                "    $GMX mdrun -deffnm em -v",
                "    if [ ! -f em.gro ]; then",
                '        echo "FATAL: Standard energy minimization failed — em.gro not produced"',
                "        exit 1",
                "    fi",
                "",
                "    # Verify EM health (detect infinite forces from bad initial geometry)",
                '    if grep -qi "force.*not finite\\|inf.*atom" em.log 2>/dev/null; then',
                '        echo "FATAL: Energy minimization failed — infinite forces detected in em.log"',
                '        echo "This usually indicates severe atomic overlaps in the initial structure."',
                '        echo "Try increasing packing padding or box size, or check Packmol logs."',
                "        exit 1",
                "    fi",
                '    echo "Standard energy minimization complete."',
                "else",
                '    echo "Skipping standard energy minimization (em.gro exists)."',
                "fi",
            ]
            return "\n".join(lines).format(grompp_flags=self._grompp_flags)

        lines = [
            "if [ ! -f em.gro ]; then",
            '    echo "=== Energy Minimization ==="',
            "    $GMX grompp -f em.mdp -c ${{PREFIX}}.gro -r ${{PREFIX}}.gro -p ${{PREFIX}}.top -o em.tpr {grompp_flags}",
            "    $GMX mdrun -deffnm em -v",
            "    if [ ! -f em.gro ]; then",
            '        echo "FATAL: Energy minimization failed — em.gro not produced"',
            "        exit 1",
            "    fi",
            "",
            "    # Verify EM health (detect infinite forces from bad initial geometry)",
            '    if grep -qi "force.*not finite\\|inf.*atom" em.log 2>/dev/null; then',
            '        echo "FATAL: Energy minimization failed — infinite forces detected in em.log"',
            '        echo "This usually indicates severe atomic overlaps in the initial structure."',
            '        echo "Try increasing packing padding or box size, or check Packmol logs."',
            "        exit 1",
            "    fi",
            '    echo "Energy minimization complete."',
            "else",
            '    echo "Skipping energy minimization (em.gro exists)."',
            "fi",
        ]
        return "\n".join(lines).format(grompp_flags=self._grompp_flags)

    def _parse_wall_time_hours(self, time_limit: str) -> float:
        """Parse SLURM wall time syntax and return hours.

        Parameters
        ----------
        time_limit : str
            SLURM time string in ``HH:MM:SS`` or ``D-HH:MM:SS`` format.

        Returns
        -------
        float
            Total wall time in hours.

        Raises
        ------
        ValueError
            If the input does not match a supported format.
        """
        days = 0
        hms_part = time_limit
        if "-" in time_limit:
            day_part, hms_part = time_limit.split("-", maxsplit=1)
            days = int(day_part)

        parts = hms_part.split(":")
        if len(parts) != 3:
            raise ValueError("Invalid SLURM time limit format. Expected HH:MM:SS or D-HH:MM:SS")

        hours, minutes, seconds = (int(part) for part in parts)
        total_hours = days * 24 + hours + (minutes / 60.0) + (seconds / 3600.0)
        return total_hours

    def _generate_equilibration_block(self, equilibration_mdps: list[str]) -> str:
        """Generate staged equilibration bash with skip-if-done behavior.

        Parameters
        ----------
        equilibration_mdps : list[str]
            Ordered list of equilibration MDP filenames.

        Returns
        -------
        str
            Rendered bash block.
        """
        lines: list[str] = ['LAST_EQ="em"']

        if not equilibration_mdps:
            lines.append(
                'echo "No equilibration stages configured; using em output for production."'
            )
            return "\n".join(lines)

        for idx, mdp_name in enumerate(equilibration_mdps, start=1):
            stage = f"eq_{idx:02d}"
            lines.append("")
            lines.append(f"if [ ! -f {stage}.gro ]; then")
            lines.append(f'    echo "=== Equilibration {idx}: {mdp_name} ==="')
            lines.append("    if [ -f ${LAST_EQ}.cpt ]; then")
            lines.append(
                f"        $GMX grompp -f {mdp_name} -c ${{LAST_EQ}}.gro -r em.gro "
                f"-t ${{LAST_EQ}}.cpt "
                f"-p ${{PREFIX}}.top -o {stage}.tpr {self._grompp_flags}"
            )
            lines.append("    else")
            lines.append(
                f"        $GMX grompp -f {mdp_name} -c ${{LAST_EQ}}.gro -r em.gro "
                f"-p ${{PREFIX}}.top -o {stage}.tpr {self._grompp_flags}"
            )
            lines.append("    fi")
            lines.append(f"    $GMX mdrun -deffnm {stage} -v")
            lines.append(f"    if [ ! -f {stage}.gro ]; then")
            lines.append(
                f'        echo "FATAL: Equilibration stage {idx} failed — {stage}.gro not produced"'
            )
            lines.append("        exit 1")
            lines.append("    fi")
            lines.append(f'    echo "Equilibration stage {idx} complete."')
            lines.append("else")
            lines.append(f'    echo "Skipping equilibration stage {idx} ({stage}.gro exists)."')
            lines.append("fi")
            lines.append(f'LAST_EQ="{stage}"')

        return "\n".join(lines)

    def save_script(self, script_content: str, output_path: Path) -> Path:
        """Save script content to disk and mark it executable.

        Parameters
        ----------
        script_content : str
            Rendered script text.
        output_path : Path
            Destination path.

        Returns
        -------
        Path
            Saved path.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script_content)
        os.chmod(output_path, 0o755)
        LOGGER.info(f"Saved GROMACS SLURM script to {output_path}")
        return output_path
