"""Covalent modification builders for PolyzyMD."""

from polyzymd.builders.conjugation.builder import CovalentModificationBuilder
from polyzymd.builders.conjugation.construction import (
    ModifierConstructionResult,
    ModifierConstructionSettings,
    construct_explicit_pdb_linkage,
    construct_modifier_linked_protein,
)
from polyzymd.builders.conjugation.contracts import (
    ExplicitLinkageContract,
    LinkageBond,
    PabloCrosslinkRequirement,
    PdbAtomSelector,
    ReactiveEndpoint,
    ResolvedAttachmentPlan,
    explicit_linkage_contract_from_config,
    parse_pdb_atom_records,
    placed_fragment_from_resolved_plan,
    resolve_explicit_linkage_contract,
)
from polyzymd.builders.conjugation.crosslinks import (
    CrosslinkValidationResult,
    ExplicitCrosslinkRequirement,
    MissingPabloCrosslinkError,
    require_explicit_pablo_crosslink,
    require_pablo_crosslink_requirement,
)
from polyzymd.builders.conjugation.diagnostics import (
    ConjugationDiagnostic,
    ConjugationDiagnosticsReport,
    DiagnosticCode,
    DiagnosticSeverity,
    write_diagnostics_report,
)
from polyzymd.builders.conjugation.exceptions import (
    ConjugationError,
    ConjugationNotImplementedError,
    PabloIngestionError,
)
from polyzymd.builders.conjugation.execution import (
    ExplicitNhsReactiveGroup,
    RdkitGraphEditExecutionRequest,
    RdkitGraphEditExecutionResult,
    RdkitGraphEditExecutionSummary,
    extract_explicit_rdkit_execution_request,
)
from polyzymd.builders.conjugation.graph import AddedBond, RdkitGraphEditResult
from polyzymd.builders.conjugation.linkers import (
    ModifierLinkageSpec,
    ModifierLinker,
    NhsLysModifierLinker,
    ProteinLinkSite,
    resolve_modifier_leaving_atoms,
    resolve_modifier_reactive_atom,
)
from polyzymd.builders.conjugation.mechanism_library import (
    get_builtin_mechanism,
    list_builtin_mechanisms,
    load_builtin_mechanisms,
)
from polyzymd.builders.conjugation.mechanisms import (
    BondSpec,
    ChargePatchHint,
    GraphEditPlan,
    MoietyReactiveGroup,
    ReactionMechanism,
    SiteAtomRule,
)
from polyzymd.builders.conjugation.metadata import (
    ChainPolicyMetadata,
    ComponentMetadata,
    ComponentRole,
    ConjugationMetadata,
    save_metadata,
)
from polyzymd.builders.conjugation.models import ConjugationBuildResult
from polyzymd.builders.conjugation.modifier import GeneratedModifierFragment, PlacedModifierFragment
from polyzymd.builders.conjugation.moieties import MoietyDescriptor, normalize_moiety_descriptor
from polyzymd.builders.conjugation.nhs_lys import (
    LysineReactiveSite,
    NhsLysGraphEditPlan,
    NhsReactiveGroup,
    detect_nhs_reactive_group,
    execute_nhs_lys_amide_rdkit_graph_edit,
    extract_lysine_reactive_site,
    plan_nhs_lys_amide,
)
from polyzymd.builders.conjugation.pablo_adapter import (
    PabloAvailability,
    PabloIngestionResult,
    PabloIngestor,
    PabloLinkCandidate,
    PabloResidueSummary,
    PabloStructureCounts,
    PabloStructurePreflight,
)
from polyzymd.builders.conjugation.parameterization import (
    InterchangeParameterizationResult,
    InterchangeParameterizationSettings,
    create_interchange_from_pablo_topology,
)
from polyzymd.builders.conjugation.pdb_assembly import (
    CrosslinkedPdbAssemblyOptions,
    CrosslinkedPdbAssemblyResult,
    NhsLysPdbAttachment,
    PdbAtomRecord,
    PdbLinkageAttachment,
    PlacedPolymerFragment,
    canonicalize_poc_residue_name,
    write_crosslinked_pdb,
)
from polyzymd.builders.conjugation.placement import (
    PackmolModifierPlacementResult,
    PackmolModifierPlacementSettings,
    place_modifier_with_packmol,
    place_modifier_with_resolved_plan,
)
from polyzymd.builders.conjugation.polymer_fragment import (
    GeneratedPolymerFragment,
    PolymerFragmentAtom,
    PolymerFragmentResidue,
)
from polyzymd.builders.conjugation.polymer_recipe import (
    POC_EGPMA_SMILES,
    POC_NHS_SMILES,
    POC_SBMA_SMILES,
    PolymeristGenerationSmokeResult,
    PolymerMonomerRecipe,
    PolymerRecipe,
    generate_polymerist_smoke_polymer,
    sbma_egpma_nhs_recipe,
)
from polyzymd.builders.conjugation.polymerist_compat import (
    ensure_polymerist_py312_compat,
    import_polymerist_building,
)
from polyzymd.builders.conjugation.polymerist_pdb import generated_fragment_from_polymerist_pdb
from polyzymd.builders.conjugation.sites import (
    AttachmentSite,
    match_site_rule,
    normalize_attachment_site,
)
from polyzymd.builders.conjugation.smoke import (
    VacuumSmokeResult,
    VacuumSmokeSettings,
    run_restrained_vacuum_smoke,
    validate_finite_energy,
    validate_finite_positions,
)
from polyzymd.builders.conjugation.structure_normalization import (
    PDBChainNormalizationAction,
    PDBCleanlinessIssue,
    PDBNormalizationPlan,
    plan_pdb_chain_normalization,
    write_normalized_pdb,
)

__all__ = [
    "AddedBond",
    "AttachmentSite",
    "BondSpec",
    "ChainPolicyMetadata",
    "ChargePatchHint",
    "ComponentMetadata",
    "ComponentRole",
    "ConjugationBuildResult",
    "ConjugationDiagnostic",
    "ConjugationDiagnosticsReport",
    "ConjugationError",
    "ConjugationMetadata",
    "ConjugationNotImplementedError",
    "CrosslinkedPdbAssemblyOptions",
    "CrosslinkedPdbAssemblyResult",
    "CrosslinkValidationResult",
    "CovalentModificationBuilder",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "ExplicitCrosslinkRequirement",
    "ExplicitLinkageContract",
    "ExplicitNhsReactiveGroup",
    "GeneratedModifierFragment",
    "GeneratedPolymerFragment",
    "GraphEditPlan",
    "InterchangeParameterizationResult",
    "InterchangeParameterizationSettings",
    "LinkageBond",
    "LysineReactiveSite",
    "MissingPabloCrosslinkError",
    "ModifierConstructionResult",
    "ModifierConstructionSettings",
    "ModifierLinkageSpec",
    "ModifierLinker",
    "MoietyDescriptor",
    "MoietyReactiveGroup",
    "NhsLysGraphEditPlan",
    "NhsLysModifierLinker",
    "NhsLysPdbAttachment",
    "NhsReactiveGroup",
    "PackmolModifierPlacementResult",
    "PackmolModifierPlacementSettings",
    "PabloCrosslinkRequirement",
    "PabloAvailability",
    "PDBChainNormalizationAction",
    "PDBCleanlinessIssue",
    "PDBNormalizationPlan",
    "PabloIngestionError",
    "PabloIngestor",
    "PabloIngestionResult",
    "PabloLinkCandidate",
    "PabloResidueSummary",
    "PabloStructureCounts",
    "PabloStructurePreflight",
    "PdbAtomRecord",
    "PdbAtomSelector",
    "PdbLinkageAttachment",
    "PlacedModifierFragment",
    "PlacedPolymerFragment",
    "POC_EGPMA_SMILES",
    "POC_NHS_SMILES",
    "POC_SBMA_SMILES",
    "PolymerFragmentAtom",
    "PolymerFragmentResidue",
    "PolymeristGenerationSmokeResult",
    "PolymerMonomerRecipe",
    "PolymerRecipe",
    "ReactionMechanism",
    "ReactiveEndpoint",
    "ResolvedAttachmentPlan",
    "RdkitGraphEditResult",
    "RdkitGraphEditExecutionRequest",
    "RdkitGraphEditExecutionResult",
    "RdkitGraphEditExecutionSummary",
    "SiteAtomRule",
    "ProteinLinkSite",
    "VacuumSmokeResult",
    "VacuumSmokeSettings",
    "save_metadata",
    "canonicalize_poc_residue_name",
    "construct_modifier_linked_protein",
    "construct_explicit_pdb_linkage",
    "create_interchange_from_pablo_topology",
    "ensure_polymerist_py312_compat",
    "detect_nhs_reactive_group",
    "execute_nhs_lys_amide_rdkit_graph_edit",
    "extract_explicit_rdkit_execution_request",
    "explicit_linkage_contract_from_config",
    "extract_lysine_reactive_site",
    "generate_polymerist_smoke_polymer",
    "generated_fragment_from_polymerist_pdb",
    "get_builtin_mechanism",
    "import_polymerist_building",
    "list_builtin_mechanisms",
    "load_builtin_mechanisms",
    "match_site_rule",
    "normalize_attachment_site",
    "normalize_moiety_descriptor",
    "parse_pdb_atom_records",
    "place_modifier_with_packmol",
    "place_modifier_with_resolved_plan",
    "placed_fragment_from_resolved_plan",
    "plan_pdb_chain_normalization",
    "plan_nhs_lys_amide",
    "require_explicit_pablo_crosslink",
    "require_pablo_crosslink_requirement",
    "resolve_explicit_linkage_contract",
    "resolve_modifier_leaving_atoms",
    "resolve_modifier_reactive_atom",
    "run_restrained_vacuum_smoke",
    "sbma_egpma_nhs_recipe",
    "validate_finite_energy",
    "validate_finite_positions",
    "write_normalized_pdb",
    "write_crosslinked_pdb",
    "write_diagnostics_report",
]
