"""Covalent modification builders for PolyzyMD."""

from polyzymd.builders.conjugation.api import build_conjugate, build_conjugate_from_config
from polyzymd.builders.conjugation.builder import CovalentModificationBuilder
from polyzymd.builders.conjugation.construction import (
    ModifierConstructionResult,
    ModifierConstructionSettings,
    construct_explicit_pdb_linkage,
    construct_modifier_linked_protein,
)
from polyzymd.builders.conjugation.contracts import (
    ExplicitLinkageContract,
    LinkageBond,
    PabloCrosslinkRequirement,
    PdbAtomSelector,
    ReactiveEndpoint,
    ResolvedAttachmentPlan,
    explicit_linkage_contract_from_config,
    parse_pdb_atom_records,
    placed_fragment_from_resolved_plan,
    resolve_explicit_linkage_contract,
)
from polyzymd.builders.conjugation.crosslinks import (
    CrosslinkValidationResult,
    ExplicitCrosslinkRequirement,
    MissingPabloCrosslinkError,
    require_explicit_pablo_crosslink,
    require_pablo_crosslink_requirement,
)
from polyzymd.builders.conjugation.diagnostics import (
    ConjugationDiagnostic,
    ConjugationDiagnosticsReport,
    DiagnosticCode,
    DiagnosticSeverity,
    write_diagnostics_report,
)
from polyzymd.builders.conjugation.engine import ConjugationEngine
from polyzymd.builders.conjugation.exceptions import (
    ConjugationError,
    ConjugationNotImplementedError,
    PabloIngestionError,
)
from polyzymd.builders.conjugation.execution import (
    ExplicitNhsReactiveGroup,
    RdkitGraphEditExecutionRequest,
    RdkitGraphEditExecutionResult,
    RdkitGraphEditExecutionSummary,
    extract_explicit_rdkit_execution_request,
)
from polyzymd.builders.conjugation.graph import AddedBond, RdkitGraphEditResult
from polyzymd.builders.conjugation.linkers import (
    ModifierLinkageSpec,
    ModifierLinker,
    NhsLysModifierLinker,
    ProteinLinkSite,
    resolve_modifier_leaving_atoms,
    resolve_modifier_nhs_atoms,
    resolve_modifier_reactive_atom,
)
from polyzymd.builders.conjugation.local_minimization import (
    product_state_pablo_crosslink_requirement,
)
from polyzymd.builders.conjugation.mechanism_library import (
    get_builtin_mechanism,
    list_builtin_mechanisms,
    load_builtin_mechanisms,
)
from polyzymd.builders.conjugation.mechanisms import (
    BondSpec,
    ChargePatchHint,
    GraphEditPlan,
    MoietyReactiveGroup,
    ReactionMechanism,
    SiteAtomRule,
)
from polyzymd.builders.conjugation.metadata import (
    ChainPolicyMetadata,
    ComponentMetadata,
    ComponentRole,
    ConjugationMetadata,
    save_metadata,
)
from polyzymd.builders.conjugation.models import (
    ConjugateBuildRequest,
    ConjugateBuildResult,
    ConjugationBuildResult,
)
from polyzymd.builders.conjugation.modifier import GeneratedModifierFragment, PlacedModifierFragment
from polyzymd.builders.conjugation.moieties import MoietyDescriptor, normalize_moiety_descriptor
from polyzymd.builders.conjugation.nhs_lys import (
    LysineReactiveSite,
    NhsLysGraphEditPlan,
    NhsReactiveGroup,
    detect_nhs_reactive_group,
    execute_nhs_lys_amide_rdkit_graph_edit,
    extract_lysine_reactive_site,
    plan_nhs_lys_amide,
)
from polyzymd.builders.conjugation.pablo_adapter import (
    PabloAvailability,
    PabloIngestionResult,
    PabloIngestor,
    PabloLinkCandidate,
    PabloResidueSummary,
    PabloStructureCounts,
    PabloStructurePreflight,
)
from polyzymd.builders.conjugation.pablo_reaction import (
    PabloProductDefinitionDiagnostic,
    PabloReactionDiagnostic,
    PabloReactionRequest,
    explore_pablo_residue_reaction,
)
from polyzymd.builders.conjugation.parameterization import (
    InterchangeParameterizationResult,
    InterchangeParameterizationSettings,
    create_interchange_from_pablo_topology,
)
from polyzymd.builders.conjugation.pdb_assembly import (
    CrosslinkedPdbAssemblyOptions,
    CrosslinkedPdbAssemblyResult,
    NhsLysPdbAttachment,
    PdbAtomRecord,
    PdbLinkageAttachment,
    PlacedPolymerFragment,
    canonicalize_poc_residue_name,
    write_crosslinked_pdb,
)
from polyzymd.builders.conjugation.placement import (
    PackmolModifierPlacementResult,
    PackmolModifierPlacementSettings,
    place_modifier_with_packmol,
    place_modifier_with_resolved_plan,
)
from polyzymd.builders.conjugation.polymer_fragment import (
    GeneratedPolymerFragment,
    PolymerFragmentAtom,
    PolymerFragmentResidue,
)
from polyzymd.builders.conjugation.polymer_recipe import (
    POC_EGPMA_SMILES,
    POC_NHS_SMILES,
    POC_SBMA_SMILES,
    PolymeristGenerationSmokeResult,
    PolymerMonomerRecipe,
    PolymerRecipe,
    generate_polymerist_smoke_polymer,
    sbma_egpma_nhs_recipe,
)
from polyzymd.builders.conjugation.polymerist_pdb import generated_fragment_from_polymerist_pdb
from polyzymd.builders.conjugation.product_pablo import (
    ProductStatePabloDefinitionSummary,
    ProductStatePabloLibrary,
    build_product_state_pablo_library,
)
from polyzymd.builders.conjugation.protein_preparation import (
    ProteinCanonicalizationResult,
    ProteinCanonicalizationSettings,
    canonicalize_protein_hydrogens,
)
from polyzymd.builders.conjugation.rdkit_inputs import (
    AtomIdentity,
    RdkitInputBundle,
    load_pdb_as_rdkit_input,
)
from polyzymd.builders.conjugation.reaction_roles import (
    STRUCTURE_MATCHING_BLOCKER_MESSAGE,
    AtomMappedReaction,
    AtomRoleSpec,
    BondChange,
    BondChangeSet,
    GenericResolvedReactionPlan,
    MappedBond,
    MappedSmartsValidation,
    PdbAtomIdentity,
    ReactionParticipant,
    ResolvedAtomRole,
    ResolvedBondChange,
    atom_mapped_reaction_from_mechanism_config,
    derive_bond_changes,
    resolve_reaction_roles_from_identity_map,
    validate_mapped_smarts,
)
from polyzymd.builders.conjugation.reactions import (
    NhsLysReaction,
    NhsLysReactionSettings,
    ReactionContext,
    ReactionResult,
    ReactionTemplate,
    get_reaction,
    list_reactions,
)
from polyzymd.builders.conjugation.sites import (
    AttachmentSite,
    match_site_rule,
    normalize_attachment_site,
)
from polyzymd.builders.conjugation.smoke import (
    VacuumSmokeResult,
    VacuumSmokeSettings,
    run_restrained_vacuum_smoke,
    validate_finite_energy,
    validate_finite_positions,
)
from polyzymd.builders.conjugation.structure_normalization import (
    PDBChainNormalizationAction,
    PDBCleanlinessIssue,
    PDBNormalizationPlan,
    plan_pdb_chain_normalization,
    write_normalized_pdb,
)
from polyzymd.builders.conjugation.system_workflow import (
    ConjugatedPolymerSystemResult,
    ConjugatedPolymerSystemSettings,
    build_conjugated_polymer_system_from_config,
    build_conjugated_polymer_system_from_config_path,
    topology_with_pdb_positions,
)

__all__ = [
    "AddedBond",
    "AtomMappedReaction",
    "AtomIdentity",
    "AtomRoleSpec",
    "AttachmentSite",
    "BondSpec",
    "BondChange",
    "BondChangeSet",
    "ChainPolicyMetadata",
    "ChargePatchHint",
    "ComponentMetadata",
    "ComponentRole",
    "ConjugateBuildRequest",
    "ConjugateBuildResult",
    "ConjugationEngine",
    "ConjugationBuildResult",
    "ConjugationDiagnostic",
    "ConjugationDiagnosticsReport",
    "ConjugationError",
    "ConjugationMetadata",
    "ConjugationNotImplementedError",
    "ConjugatedPolymerSystemResult",
    "ConjugatedPolymerSystemSettings",
    "CrosslinkedPdbAssemblyOptions",
    "CrosslinkedPdbAssemblyResult",
    "CrosslinkValidationResult",
    "CovalentModificationBuilder",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "ExplicitCrosslinkRequirement",
    "ExplicitLinkageContract",
    "ExplicitNhsReactiveGroup",
    "GeneratedModifierFragment",
    "GeneratedPolymerFragment",
    "GenericResolvedReactionPlan",
    "GraphEditPlan",
    "InterchangeParameterizationResult",
    "InterchangeParameterizationSettings",
    "LinkageBond",
    "LysineReactiveSite",
    "MissingPabloCrosslinkError",
    "ModifierConstructionResult",
    "ModifierConstructionSettings",
    "ModifierLinkageSpec",
    "ModifierLinker",
    "MoietyDescriptor",
    "MoietyReactiveGroup",
    "NhsLysGraphEditPlan",
    "NhsLysModifierLinker",
    "NhsLysPdbAttachment",
    "NhsLysReaction",
    "NhsLysReactionSettings",
    "NhsReactiveGroup",
    "PackmolModifierPlacementResult",
    "PackmolModifierPlacementSettings",
    "PabloCrosslinkRequirement",
    "PabloAvailability",
    "PabloProductDefinitionDiagnostic",
    "PabloReactionDiagnostic",
    "PabloReactionRequest",
    "PDBChainNormalizationAction",
    "PDBCleanlinessIssue",
    "PDBNormalizationPlan",
    "PabloIngestionError",
    "PabloIngestor",
    "PabloIngestionResult",
    "PabloLinkCandidate",
    "PabloResidueSummary",
    "PabloStructureCounts",
    "PabloStructurePreflight",
    "PdbAtomRecord",
    "PdbAtomIdentity",
    "PdbAtomSelector",
    "PdbLinkageAttachment",
    "PlacedModifierFragment",
    "PlacedPolymerFragment",
    "POC_EGPMA_SMILES",
    "POC_NHS_SMILES",
    "POC_SBMA_SMILES",
    "PolymerFragmentAtom",
    "PolymerFragmentResidue",
    "PolymeristGenerationSmokeResult",
    "PolymerMonomerRecipe",
    "PolymerRecipe",
    "ProductStatePabloDefinitionSummary",
    "ProductStatePabloLibrary",
    "ProteinCanonicalizationResult",
    "ProteinCanonicalizationSettings",
    "ReactionMechanism",
    "ReactionContext",
    "ReactionResult",
    "ReactionParticipant",
    "ReactionTemplate",
    "ReactiveEndpoint",
    "ResolvedAttachmentPlan",
    "ResolvedAtomRole",
    "ResolvedBondChange",
    "RdkitInputBundle",
    "RdkitGraphEditResult",
    "RdkitGraphEditExecutionRequest",
    "RdkitGraphEditExecutionResult",
    "RdkitGraphEditExecutionSummary",
    "MappedBond",
    "MappedSmartsValidation",
    "STRUCTURE_MATCHING_BLOCKER_MESSAGE",
    "SiteAtomRule",
    "ProteinLinkSite",
    "VacuumSmokeResult",
    "VacuumSmokeSettings",
    "save_metadata",
    "build_conjugate",
    "build_conjugate_from_config",
    "canonicalize_protein_hydrogens",
    "canonicalize_poc_residue_name",
    "build_conjugated_polymer_system_from_config",
    "build_conjugated_polymer_system_from_config_path",
    "build_product_state_pablo_library",
    "construct_modifier_linked_protein",
    "construct_explicit_pdb_linkage",
    "create_interchange_from_pablo_topology",
    "atom_mapped_reaction_from_mechanism_config",
    "derive_bond_changes",
    "detect_nhs_reactive_group",
    "explore_pablo_residue_reaction",
    "execute_nhs_lys_amide_rdkit_graph_edit",
    "extract_explicit_rdkit_execution_request",
    "explicit_linkage_contract_from_config",
    "extract_lysine_reactive_site",
    "generate_polymerist_smoke_polymer",
    "generated_fragment_from_polymerist_pdb",
    "get_reaction",
    "get_builtin_mechanism",
    "list_builtin_mechanisms",
    "load_pdb_as_rdkit_input",
    "list_reactions",
    "load_builtin_mechanisms",
    "match_site_rule",
    "normalize_attachment_site",
    "normalize_moiety_descriptor",
    "parse_pdb_atom_records",
    "place_modifier_with_packmol",
    "place_modifier_with_resolved_plan",
    "placed_fragment_from_resolved_plan",
    "plan_pdb_chain_normalization",
    "plan_nhs_lys_amide",
    "product_state_pablo_crosslink_requirement",
    "require_explicit_pablo_crosslink",
    "require_pablo_crosslink_requirement",
    "resolve_explicit_linkage_contract",
    "resolve_reaction_roles_from_identity_map",
    "resolve_modifier_leaving_atoms",
    "resolve_modifier_nhs_atoms",
    "resolve_modifier_reactive_atom",
    "run_restrained_vacuum_smoke",
    "sbma_egpma_nhs_recipe",
    "topology_with_pdb_positions",
    "validate_mapped_smarts",
    "validate_finite_energy",
    "validate_finite_positions",
    "write_normalized_pdb",
    "write_crosslinked_pdb",
    "write_diagnostics_report",
]
