"""Adapter that runs a contract plugin inside the current analysis lifecycle.

:func:`contract_analysis` turns an object that satisfies
:class:`~polyzymd.analyses.contract.AnalysisProtocol` into an
:class:`~polyzymd.analyses.base.Analysis` subclass, so ``polyzymd compare run``,
the artifact store and the HPC worker commands keep working while the plugin
itself stays a settings model plus one ``compute`` function.

The adapter owns what every plugin used to repeat: it writes the replicate
artifact with a framework-written identity block, reuses a replicate whose
identity still matches, aggregates by observable kind, compares with the
configured test under one Benjamini-Hochberg family, and formats the result.
"""

from __future__ import annotations

import hashlib
import inspect
import logging
from abc import abstractmethod
from pathlib import Path
from typing import Any, ClassVar, Sequence

from pydantic import BaseModel

from polyzymd.analyses.base import Analysis
from polyzymd.analyses.contract import (
    AnalysisProtocol,
    Observable,
    ObservableAggregate,
    ObservableEstimate,
    aggregate_observables,
    compare_observables,
    reduce_observable,
)
from polyzymd.analyses.exceptions import PluginContractError
from polyzymd.analyses.mda.artifacts import (
    ArtifactSidecarRef,
    ComparisonArtifact,
    ConditionArtifact,
    ReplicateArtifact,
)
from polyzymd.analyses.mda.job import MDAAnalysisJob
from polyzymd.analyses.mda.plugin import frame_selection_payload
from polyzymd.analyses.mda.store import ArtifactStore

logger = logging.getLogger("polyzymd.analyses")

#: Identity fields that must match before a cached replicate is reused.
_CACHE_KEYS = ("polyzymd_version", "plugin_code_hash", "settings_fingerprint", "config_hash")


class ContractAnalysis(Analysis):
    """Lifecycle implementation shared by every contract plugin.

    Subclasses are generated by :func:`contract_analysis` and differ only in
    ``name``, ``Settings`` and the ``plugin`` they hold.
    """

    min_replicates: ClassVar[int] = 1

    @property
    @abstractmethod
    def plugin(self) -> AnalysisProtocol:
        """Return the contract plugin this analysis runs."""

    def build_mda_jobs(self, ctx: Any) -> Sequence[MDAAnalysisJob]:
        """Wrap ``plugin.compute`` as the single MDAnalysis job of a replicate.

        Parameters
        ----------
        ctx : MDAReplicateJobContext
            Context with the loaded universe, the frame selection and the
            replicate artifact store.

        Returns
        -------
        Sequence[MDAAnalysisJob]
            One job whose results hold the reduced observables and a reference
            to the NPZ sidecar with the full per-frame series.
        """

        def run(universe: Any, **frame_kwargs: Any) -> dict[str, Any]:
            del frame_kwargs
            observables = _validated(
                self.plugin.compute(universe, ctx.frame_selection, ctx.settings)
            )
            estimates = [reduce_observable(observable) for observable in observables]
            sidecar = ctx.artifact_store.write_npz_sidecar(
                "observables.npz",
                **{observable.name: observable.values for observable in observables},
            )
            return {
                "observables": [estimate.model_dump(mode="json") for estimate in estimates],
                "sidecars": [sidecar.model_dump(mode="json")],
            }

        return [
            MDAAnalysisJob.from_function(
                self.name, run, ctx.universe, frame_selection=ctx.frame_selection
            )
        ]

    def build_mda_collector(self, ctx: Any) -> Any:
        """Return the collector that writes the replicate artifact.

        Parameters
        ----------
        ctx : MDACollectorContext
            Context for one replicate, carrying the identity the framework
            stamps onto the artifact.

        Returns
        -------
        Callable
            Collector accepted by the MDAnalysis job lifecycle.
        """
        identity = self._identity(
            ctx.replicate_context.sim_config,
            ctx.replicate_context.settings,
            ctx.replicate_context.equilibration,
        )
        identity["inputs"] = _input_identity(ctx.universe_policy.as_dict())

        def collect(collector_ctx: Any, completed_jobs: Sequence[Any]) -> ReplicateArtifact:
            results = completed_jobs[0].results
            return ReplicateArtifact(
                analysis_name=collector_ctx.analysis_name,
                condition_label=collector_ctx.condition_label,
                replicate=collector_ctx.replicate,
                payload={"observables": results["observables"]},
                sidecars=[
                    ArtifactSidecarRef.model_validate(ref) for ref in results.get("sidecars", [])
                ],
                provenance={
                    "source": "observable_contract",
                    "identity": identity,
                    "frame_selection": frame_selection_payload(collector_ctx.frame_selection),
                    "universe_policy": collector_ctx.universe_policy.as_dict(),
                },
                metadata={
                    "result_kind": "observables",
                    "settings_fingerprint": collector_ctx.settings_fingerprint,
                },
                warnings=list(collector_ctx.warnings),
            )

        return collect

    def aggregate(self, ctx: Any, results: Sequence[Any]) -> ConditionArtifact:
        """Summarize the replicates of one condition by observable kind.

        Parameters
        ----------
        ctx : AggregateContext
            Framework aggregation context.
        results : Sequence[ReplicateArtifact]
            Replicate artifacts written by the compute stage.

        Returns
        -------
        ConditionArtifact
            Artifact whose payload holds one
            :class:`~polyzymd.analyses.contract.ObservableAggregate` per
            observable.
        """
        replicates = [_estimates(result) for result in results]
        aggregates = aggregate_observables(replicates)
        return ConditionArtifact(
            analysis_name=self.name,
            condition_label=ctx.condition.label,
            replicates=[int(replicate) for replicate in ctx.replicates],
            payload={
                "observables": [aggregate.model_dump(mode="json") for aggregate in aggregates]
            },
            provenance={
                "source": "observable_contract",
                "identity": _first_identity(results),
            },
            metadata={
                "settings_fingerprint": self.aggregate_settings_fingerprint(ctx.settings),
                "equilibration": ctx.equilibration,
                "n_replicates": len(replicates),
            },
        )

    def compare(self, ctx: Any) -> ComparisonArtifact | None:
        """Test every observable across conditions with one correction family.

        Parameters
        ----------
        ctx : ComparisonContext
            Framework comparison context carrying the configured test, the
            post-hoc method and the alpha.

        Returns
        -------
        ComparisonArtifact or None
            Comparison artifact, or ``None`` when fewer than two conditions
            have an aggregate on disk.
        """
        by_condition: dict[str, list[ObservableAggregate]] = {}
        for condition in ctx.conditions:
            artifact = ctx.aggregated_results.get(condition.label)
            if artifact is None:
                directory = ctx.analysis_dirs.get(condition.label)
                artifact = (
                    None
                    if directory is None
                    else self._load_aggregated_result(directory / "aggregated")
                )
            if artifact is None:
                logger.warning("%s: no aggregate for %r, skipping", self.name, condition.label)
                continue
            by_condition[condition.label] = [
                ObservableAggregate.model_validate(payload)
                for payload in artifact.payload["observables"]
            ]
        if len(by_condition) < 2:
            return None
        comparisons = compare_observables(
            by_condition,
            control_label=ctx.effective_control,
            ttest_method=ctx.ttest_method,
            posthoc_method=ctx.posthoc_method,
            fdr_alpha=ctx.fdr_alpha,
        )
        return ComparisonArtifact(
            analysis_name=self.name,
            conditions=list(by_condition),
            control_label=ctx.control_label,
            effective_control=ctx.effective_control,
            payload={
                "conditions": {
                    label: [aggregate.model_dump(mode="json") for aggregate in aggregates]
                    for label, aggregates in by_condition.items()
                },
                "comparisons": [comparison.model_dump(mode="json") for comparison in comparisons],
            },
            metadata={
                "equilibration": ctx.equilibration,
                "fdr_alpha": ctx.fdr_alpha,
                "ttest_method": ctx.ttest_method,
                "posthoc_method": ctx.posthoc_method,
                "references": list(getattr(self.plugin, "references", ())),
            },
        )

    def format(self, result: Any, output_format: str = "text") -> str:
        """Render a comparison artifact as text or JSON.

        Parameters
        ----------
        result : ComparisonArtifact
            Comparison artifact produced by :meth:`compare`.
        output_format : str, optional
            ``"text"`` or ``"json"``, by default ``"text"``.

        Returns
        -------
        str
            Rendered report. Every line states its unit and its replicate
            count, and comparison lines state the adjusted p-value.
        """
        if output_format == "json" or not isinstance(result, ComparisonArtifact):
            return super().format(result, output_format)
        lines = [f"# {self.name}  eq {result.metadata.get('equilibration')}"]
        for label, payloads in result.payload["conditions"].items():
            for payload in payloads:
                lines.append(
                    f"{label}  {_format_aggregate(ObservableAggregate.model_validate(payload))}"
                )
        for payload in result.payload["comparisons"]:
            lines.append(_format_comparison(payload))
        return "\n".join(lines)

    def _run_compute_stage(self, ctx: Any, replicate: int) -> Any:
        """Reuse a replicate whose identity still matches, otherwise compute it."""
        cached = self._reusable(ctx)
        if cached is not None:
            logger.info("%s: reusing replicate %d from cache", self.name, replicate)
            return cached
        return super()._run_compute_stage(ctx, replicate)

    def _reusable(self, ctx: Any) -> ReplicateArtifact | None:
        """Load the cached replicate artifact when its identity block matches."""
        path = ctx.result_path or self.replicate_result_path(ctx.output_dir)
        if ctx.recompute or not Path(path).exists():
            return None
        try:
            artifact = ArtifactStore(ctx.output_dir).read_replicate_result(
                Path(path).relative_to(ctx.output_dir)
            )
        except Exception:
            return None
        stored = artifact.provenance.get("identity", {})
        current = self._identity(ctx.sim_config, ctx.settings, ctx.equilibration)
        if any(stored.get(key) != current[key] for key in _CACHE_KEYS):
            return None
        return artifact if stored.get("equilibration") == current["equilibration"] else None

    def _identity(self, sim_config: Any, settings: BaseModel, equilibration: str) -> dict[str, Any]:
        """Build the framework-written identity block for one replicate."""
        from polyzymd import __version__
        from polyzymd.analyses._framework.cache_identity import compute_config_hash

        return {
            "polyzymd_version": __version__,
            "plugin": self.name,
            "plugin_code_hash": _code_hash(self.plugin),
            "settings_fingerprint": self.aggregate_settings_fingerprint(settings),
            "config_hash": compute_config_hash(sim_config),
            "equilibration": equilibration,
        }


def contract_analysis(plugin: Any) -> type[ContractAnalysis]:
    """Build the ``Analysis`` subclass that runs a contract plugin.

    Parameters
    ----------
    plugin : AnalysisProtocol
        Plugin class or instance with ``name``, ``Settings`` and ``compute``.

    Returns
    -------
    type[ContractAnalysis]
        Concrete analysis class for plugin discovery. Assign it to a
        module-level name so ``polyzymd.analyses.discovery`` finds it.

    Raises
    ------
    PluginContractError
        If the plugin is missing ``name``, ``Settings`` or ``compute``, or if
        ``Settings`` is not a pydantic model.
    """
    instance = plugin() if isinstance(plugin, type) else plugin
    name = getattr(instance, "name", "")
    settings_cls = getattr(instance, "Settings", None)
    if not isinstance(name, str) or not name.strip():
        raise PluginContractError(f"{type(instance).__name__} must define name as a string")
    if not (isinstance(settings_cls, type) and issubclass(settings_cls, BaseModel)):
        raise PluginContractError(f"{name}.Settings must be a pydantic BaseModel subclass")
    if not callable(getattr(instance, "compute", None)):
        raise PluginContractError(f"{name} must define compute(universe, frames, settings)")
    return type(
        f"{_class_prefix(name)}ContractAnalysis",
        (ContractAnalysis,),
        {
            "name": name,
            "Settings": settings_cls,
            "plugin": instance,
            "references": tuple(getattr(instance, "references", ())),
            "__doc__": inspect.getdoc(instance) or f"Contract analysis {name}.",
        },
    )


def _validated(observables: Any) -> list[Observable]:
    """Reject a compute() return value that is not a sequence of observables."""
    if isinstance(observables, Observable) or not isinstance(observables, Sequence):
        raise PluginContractError("compute() must return a sequence of Observable objects")
    invalid = [type(item).__name__ for item in observables if not isinstance(item, Observable)]
    if invalid or not observables:
        raise PluginContractError(
            f"compute() must return at least one Observable, got {invalid or 'an empty sequence'}"
        )
    return list(observables)


def _estimates(result: Any) -> list[ObservableEstimate]:
    """Read the reduced observables back out of one replicate artifact."""
    if not isinstance(result, ReplicateArtifact):
        raise PluginContractError(f"expected a ReplicateArtifact, got {type(result).__name__}")
    return [
        ObservableEstimate.model_validate(payload)
        for payload in result.payload.get("observables", [])
    ]


def _first_identity(results: Sequence[Any]) -> dict[str, Any]:
    """Identity block of the first replicate, minus its per-file entries."""
    for result in results:
        identity = dict(getattr(result, "provenance", {}).get("identity", {}))
        identity.pop("inputs", None)
        if identity:
            return identity
    return {}


def _input_identity(policy: dict[str, Any]) -> list[dict[str, Any]]:
    """Topology and trajectory file identities recorded by the universe provider."""
    provenance = policy.get("provenance")
    if not isinstance(provenance, dict):
        return []
    topology = provenance.get("topology")
    trajectories = provenance.get("trajectories") or []
    files = ([topology] if isinstance(topology, dict) else []) + list(trajectories)
    return [dict(entry) for entry in files if isinstance(entry, dict)]


def _code_hash(plugin: Any) -> str:
    """Short SHA-256 of the plugin source, so a fixed bug invalidates caches."""
    try:
        source = inspect.getsource(type(plugin))
    except (OSError, TypeError):
        return "unknown"
    return hashlib.sha256(source.encode("utf-8")).hexdigest()[:16]


def _class_prefix(name: str) -> str:
    """PascalCase prefix derived from a snake_case analysis name."""
    return "".join(part.capitalize() for part in name.split("_"))


def _format_aggregate(aggregate: ObservableAggregate) -> str:
    """One line describing a condition-level aggregate, keyed on kind."""
    unit = f" {aggregate.unit}" if aggregate.unit else ""
    if aggregate.kind == "profile":
        return f"{aggregate.name}  profile over {len(aggregate.index or [])} indices  n {aggregate.n_replicates}"
    interval = (
        ""
        if aggregate.ci95_low is None
        else f"  ci95 {aggregate.ci95_low:.4g} to {aggregate.ci95_high:.4g}"
    )
    sem = "" if aggregate.sem is None else f"  sem {aggregate.sem:.4g}"
    return (
        f"{aggregate.name}  {aggregate.kind}  mean {aggregate.mean:.4g}{unit}"
        f"{sem}{interval}  n {aggregate.n_replicates}"
    )


def _format_comparison(payload: dict[str, Any]) -> str:
    """One line describing a pairwise test, always naming the adjusted p-value."""
    delta = payload.get("delta")
    p_adjusted = payload.get("p_adjusted")
    verdict = "significant" if payload.get("significant") else "no significant difference"
    return (
        f"{payload['control']} vs {payload['condition']}  {payload['name']}  "
        f"delta {'n/a' if delta is None else format(delta, '+.4g')}  "
        f"p_adj {'n/a' if p_adjusted is None else format(p_adjusted, '.4g')}  "
        f"test {payload['test']}  correction {payload['correction']}  {verdict}"
    )
