"""Scaffold generator for new analysis plugins.

Creates the minimal file set needed for a new analysis plugin:
- ``src/polyzymd/analyses/<name>/__init__.py``  — plugin class with compute,
  aggregate, comparison, and plotting methods
- ``tests/analyses/plugins/test_<name>.py``  — smoke tests covering discovery,
  compute, aggregate, metrics, and plotting

Two styles are available via the ``--style`` flag:

- **dict** (default) — Plain dicts for results, no Pydantic result models.
  Simplest starting point for new contributors.
- **pydantic** — Typed Pydantic result models (``ReplicateResult``,
  ``AggregatedResult``) with ``AggregatedResultClass``.  Better for complex
  analyses that need validation and IDE autocomplete.

Per-analysis plot settings (``_plot_settings.py``) are **not** generated by
default.  They are optional and only needed if you want per-analysis
customization fields accessible via ``plot_settings.<name>`` in
``comparison.yaml``.  See existing plugins like ``rmsf/_plot_settings.py``
for examples.

Usage::

    polyzymd new-analysis my_analysis
    polyzymd new-analysis my_analysis --style pydantic
    polyzymd new-analysis my_analysis --dry-run
    polyzymd new-analysis my_analysis --force
"""

from __future__ import annotations

import keyword
import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Name helpers
# ---------------------------------------------------------------------------

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

_RESERVED_NAMES = frozenset(
    {
        "base",
        "cli",
        "config",
        "discovery",
        "orchestrator",
        "runner",
        "shared",
        "stats",
    }
)

VALID_STYLES = ("dict", "pydantic")


def validate_name(name: str, *, check_existing: bool = True) -> str | None:
    """Return an error message if *name* is not a valid plugin name, else None.

    Parameters
    ----------
    name : str
        Proposed plugin name in snake_case.
    check_existing : bool
        If True, also reject names that collide with already-registered
        analysis plugins or their aliases.
    """
    if not _NAME_RE.match(name):
        return (
            f"'{name}' is not a valid plugin name. Use lowercase snake_case (e.g. 'my_analysis')."
        )
    if keyword.iskeyword(name):
        return f"'{name}' is a Python keyword."
    if name in _RESERVED_NAMES:
        return f"'{name}' is reserved for framework infrastructure."
    if check_existing:
        try:
            from polyzymd.analyses.discovery import list_all_names

            if name in list_all_names():
                return f"'{name}' already exists as a registered analysis plugin."
        except ImportError:
            pass  # Discovery module not available (e.g. minimal install)
    return None


def validate_class_name(class_name: str) -> str | None:
    """Return an error message if *class_name* is not a valid class prefix, else None.

    Parameters
    ----------
    class_name : str
        Proposed PascalCase class prefix (e.g. ``SolventShell``).
        Will be used as ``<class_name>Analysis``, ``<class_name>Settings``, etc.
    """
    if not class_name.isidentifier():
        return (
            f"'{class_name}' is not a valid Python identifier. "
            "Use PascalCase (e.g. 'SolventShell')."
        )
    if keyword.iskeyword(class_name):
        return f"'{class_name}' is a Python keyword and cannot be used as a class name."
    if not class_name[0].isupper():
        return f"'{class_name}' should start with an uppercase letter (PascalCase convention)."
    return None


def to_pascal_case(snake: str) -> str:
    """Convert ``snake_case`` to ``PascalCase``."""
    return "".join(part.capitalize() for part in snake.split("_"))


# ---------------------------------------------------------------------------
# Templates — dict style (default, recommended for new contributors)
# ---------------------------------------------------------------------------


def _plugin_init_dict(name: str, cls: str) -> str:
    return f'''"""{name.replace("_", " ").title()} analysis plugin.

Uses plain dicts for results.  This is the simplest starting point.
Migrate to Pydantic result models later if you need typed attribute
access, validation, or NPZ sidecar storage.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, ClassVar, Sequence

from pydantic import BaseModel, Field

from polyzymd.analyses.base import (
    AggregateContext,
    Analysis,
    ComparisonResult,
    MetricValue,
    PlotContext,
    ReplicateContext,
)
from polyzymd.analyses.stats import format_scalar_comparison

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Plugin
# ---------------------------------------------------------------------------


class {cls}Analysis(Analysis):
    """{name.replace("_", " ").title()} analysis plugin.

    Implements the full analysis lifecycle: per-replicate computation,
    cross-replicate aggregation, and cross-condition comparison.

    Uses plain dicts for results — no ``AggregatedResultClass`` needed.
    """

    name: ClassVar[str] = "{name}"

    class Settings(BaseModel):
        """Settings for the {name} analysis.

        Add analysis-specific fields here.  These are resolved from the
        ``comparison.yaml`` plugins section.
        """

        example_parameter: str = Field(
            default="dummy",
            description="Replace with real settings for your analysis.",
        )

    # -- lifecycle methods ---------------------------------------------------

    def compute_replicate(
        self,
        ctx: ReplicateContext,
        replicate: int,
    ) -> dict[str, Any]:
        """Compute results for a single replicate.

        Replace with real per-replicate computation.
        """
        return {{
            "value": 1.0,
            "replicate": replicate,
            "example_parameter": ctx.settings.example_parameter,
        }}

    def aggregate(
        self,
        ctx: AggregateContext,
        results: Sequence[Any],
    ) -> dict[str, Any]:
        """Aggregate replicate results for one condition.

        Replace with real aggregation logic.
        """
        values = [float(r["value"]) for r in results]
        n = len(values)
        if n == 0:
            raise ValueError("aggregate() received no results — cannot compute statistics.")
        mean = sum(values) / n
        sem = 0.0
        if n > 1:
            variance = sum((v - mean) ** 2 for v in values) / (n - 1)
            sem = (variance ** 0.5) / (n ** 0.5)
        return {{
            "mean_value": mean,
            "sem_value": sem,
            "replicate_values": values,
        }}

    # -- comparison ----------------------------------------------------------

    def extract_metrics(self, summary: Any) -> dict[str, MetricValue]:
        """Expose scalar metrics for the default comparison pipeline.

        The default ``compare()`` loads aggregated results as dicts
        via ``json.loads()`` and passes them here.
        """
        return {{
            "value": MetricValue(
                name="value",
                mean=float(summary["mean_value"]),
                sem=float(summary["sem_value"]),
                replicate_values=[float(v) for v in summary["replicate_values"]],
                higher_is_better=True,
                direction_labels=("decreased", "unchanged", "increased"),
            )
        }}

    # -- formatting ----------------------------------------------------------

    def format(self, result: Any, output_format: str = "text") -> str:
        """Format comparison result for CLI display."""
        if isinstance(result, ComparisonResult):
            return format_scalar_comparison(
                result,
                title="{name.replace("_", " ").title()} Comparison",
                metric_label="Mean Value",
                metric_unit="",
                metric_key="value",
                output_format=output_format,
                higher_is_better=True,
            )
        return super().format(result, output_format)

    # -- plotting ------------------------------------------------------------

    def plot(self, ctx: PlotContext) -> list[Path]:
        """Generate comparison figures.

        Uses ``_build_plot_data()`` from the ``Analysis`` base class to
        load aggregated results for each condition, then creates a bar
        chart.  Replace this with your own plotting logic.

        As your plugin grows, extract plotting functions into a
        ``_plotters.py`` module within the package.
        """
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        from polyzymd.analyses.shared import apply_axis_style, get_colors, get_output_path, save_figure

        # _build_plot_data() collects analysis_dir / aggregated_dir per condition
        data, labels = self._build_plot_data(ctx)
        if not labels:
            return []

        # Collect per-condition aggregated values
        means: list[float] = []
        sems: list[float] = []
        valid_labels: list[str] = []
        for label in labels:
            if label not in data or label == "__meta__":
                continue
            agg_dir = data[label]["aggregated_dir"]
            summary = self._load_aggregated_result(agg_dir)
            if summary is None:
                continue
            means.append(float(summary["mean_value"]))
            sems.append(float(summary["sem_value"]))
            valid_labels.append(label)

        if not valid_labels:
            return []

        plot_settings = ctx.plot_settings
        colors = get_colors(len(valid_labels), plot_settings)

        fig, ax = plt.subplots(figsize=(8, 5))
        ax.bar(valid_labels, means, yerr=sems, capsize=5, color=colors[: len(valid_labels)])
        apply_axis_style(ax, plot_settings, title="{name.replace("_", " ").title()} Comparison", ylabel="Value")

        output_path = get_output_path(ctx.output_dir, "{name}_comparison", plot_settings)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        save_figure(fig, output_path, plot_settings)
        return [output_path]
'''


def _test_file_dict(name: str, cls: str) -> str:
    return f'''"""Tests for the {name} analysis plugin (dict style)."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from polyzymd.analyses.base import (
    AggregateContext,
    Condition,
    MetricValue,
    PlotContext,
    ReplicateContext,
)
from polyzymd.analyses.discovery import clear_cache, get_analysis
from polyzymd.analyses.shared import PlotSettings


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def analysis():
    cls = get_analysis("{name}")
    return cls()


@pytest.fixture
def settings():
    cls = get_analysis("{name}")
    return cls.Settings()


@pytest.fixture
def plot_settings() -> PlotSettings:
    return PlotSettings()


@pytest.fixture
def condition(tmp_path: Path) -> Condition:
    return Condition(
        label="Condition A",
        config_path=tmp_path / "config.yaml",
        replicates=(1, 2),
        sim_config=MagicMock(),
    )


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------


class TestDiscovery:
    def test_discoverable_by_name(self):
        clear_cache()
        analysis_cls = get_analysis("{name}")
        assert analysis_cls.name == "{name}"

    def test_settings_type(self):
        analysis_cls = get_analysis("{name}")
        assert hasattr(analysis_cls, "Settings")


# ---------------------------------------------------------------------------
# Compute
# ---------------------------------------------------------------------------


class TestComputeReplicate:
    def test_returns_dict(self, analysis, settings, condition, tmp_path):
        ctx = ReplicateContext(
            condition=condition,
            replicate=1,
            sim_config=condition.sim_config,
            output_dir=tmp_path / "run_1",
            equilibration="0ns",
            recompute=True,
            settings=settings,
        )
        result = analysis.compute_replicate(ctx, 1)

        assert isinstance(result, dict)
        assert result["replicate"] == 1
        assert result["value"] == pytest.approx(1.0)
        assert result["example_parameter"] == "dummy"


# ---------------------------------------------------------------------------
# Aggregate
# ---------------------------------------------------------------------------


class TestAggregate:
    def test_aggregate_two_replicates(self, analysis, settings, condition, tmp_path):
        ctx = AggregateContext(
            condition=condition,
            replicates=(1, 2),
            output_dir=tmp_path / "aggregated",
            equilibration="0ns",
            settings=settings,
        )
        results = [
            {{"value": 1.0, "replicate": 1}},
            {{"value": 3.0, "replicate": 2}},
        ]
        summary = analysis.aggregate(ctx, results)

        assert isinstance(summary, dict)
        assert summary["mean_value"] == pytest.approx(2.0)
        assert summary["replicate_values"] == [1.0, 3.0]


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


class TestExtractMetrics:
    def test_returns_metric_value(self, analysis):
        summary = {{
            "mean_value": 2.0,
            "sem_value": 0.5,
            "replicate_values": [1.0, 3.0],
        }}
        metrics = analysis.extract_metrics(summary)

        assert "value" in metrics
        assert isinstance(metrics["value"], MetricValue)
        assert metrics["value"].mean == pytest.approx(2.0)
        assert metrics["value"].sem == pytest.approx(0.5)


# ---------------------------------------------------------------------------
# Plot
# ---------------------------------------------------------------------------


class TestPlot:
    def test_plot_produces_figure(self, analysis, settings, plot_settings, tmp_path):
        """Plot with two conditions produces a comparison PNG."""
        conditions = []
        analysis_dirs = {{}}

        for label, mean, sem in [("Cond_A", 2.0, 0.3), ("Cond_B", 4.0, 0.5)]:
            cond = Condition(
                label=label,
                config_path=tmp_path / "config.yaml",
                replicates=(1, 2),
                sim_config=MagicMock(),
            )
            conditions.append(cond)

            agg_dir = tmp_path / label / "{name}" / "aggregated"
            agg_dir.mkdir(parents=True)
            (agg_dir / "result.json").write_text(
                json.dumps({{
                    "mean_value": mean,
                    "sem_value": sem,
                    "replicate_values": [mean - 0.1, mean + 0.1],
                }}),
                encoding="utf-8",
            )
            analysis_dirs[label] = tmp_path / label / "{name}"

        ctx = PlotContext(
            conditions=conditions,
            analysis_dirs=analysis_dirs,
            output_dir=tmp_path / "figures",
            results_dir=tmp_path / "results",
            settings=settings,
            plot_settings=plot_settings,
        )

        paths = analysis.plot(ctx)

        assert len(paths) == 1
        assert paths[0].exists()
        assert paths[0].suffix == ".png"

    def test_plot_returns_empty_when_no_data(self, analysis, settings, plot_settings, tmp_path):
        """Plot with no aggregated results returns empty list."""
        cond = Condition(
            label="Empty",
            config_path=tmp_path / "config.yaml",
            replicates=(1,),
            sim_config=MagicMock(),
        )
        analysis_dirs = {{"Empty": tmp_path / "Empty" / "{name}"}}
        (tmp_path / "Empty" / "{name}" / "aggregated").mkdir(parents=True)

        ctx = PlotContext(
            conditions=[cond],
            analysis_dirs=analysis_dirs,
            output_dir=tmp_path / "figures",
            results_dir=tmp_path / "results",
            settings=settings,
            plot_settings=plot_settings,
        )

        paths = analysis.plot(ctx)
        assert paths == []
'''


# ---------------------------------------------------------------------------
# Templates — pydantic style (typed result models)
# ---------------------------------------------------------------------------


def _plugin_init_pydantic(name: str, cls: str) -> str:
    return f'''"""{name.replace("_", " ").title()} analysis plugin.

Uses typed Pydantic result models for validation and IDE autocomplete.
Set ``AggregatedResultClass`` so the framework deserializes aggregated
results into the typed model automatically.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, ClassVar, Sequence

from pydantic import BaseModel, Field

from polyzymd.analyses.base import (
    AggregateContext,
    Analysis,
    ComparisonResult,
    MetricValue,
    PlotContext,
    ReplicateContext,
)
from polyzymd.analyses.stats import format_scalar_comparison

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Result models
# ---------------------------------------------------------------------------


class {cls}ReplicateResult(BaseModel):
    """Result from a single replicate of {name} analysis."""

    replicate: int
    value: float
    example_parameter: str = ""


class {cls}AggregatedResult(BaseModel):
    """Aggregated {name} result across replicates."""

    mean_value: float
    sem_value: float
    replicate_values: list[float]


# ---------------------------------------------------------------------------
# Plugin
# ---------------------------------------------------------------------------


class {cls}Analysis(Analysis):
    """{name.replace("_", " ").title()} analysis plugin.

    Implements the full analysis lifecycle: per-replicate computation,
    cross-replicate aggregation, and cross-condition comparison.
    """

    name: ClassVar[str] = "{name}"
    AggregatedResultClass: ClassVar[type] = {cls}AggregatedResult

    class Settings(BaseModel):
        """Settings for the {name} analysis.

        Add analysis-specific fields here.  These are resolved from the
        ``comparison.yaml`` plugins section.
        """

        example_parameter: str = Field(
            default="dummy",
            description="Replace with real settings for your analysis.",
        )

    # -- lifecycle methods ---------------------------------------------------

    def compute_replicate(
        self,
        ctx: ReplicateContext,
        replicate: int,
    ) -> {cls}ReplicateResult:
        """Compute results for a single replicate.

        Replace with real per-replicate computation.
        """
        return {cls}ReplicateResult(
            replicate=replicate,
            value=1.0,
            example_parameter=ctx.settings.example_parameter,
        )

    def aggregate(
        self,
        ctx: AggregateContext,
        results: Sequence[Any],
    ) -> {cls}AggregatedResult:
        """Aggregate replicate results for one condition.

        Replace with real aggregation logic.
        """
        values = [float(r.value if hasattr(r, "value") else r["value"]) for r in results]
        n = len(values)
        if n == 0:
            raise ValueError("aggregate() received no results — cannot compute statistics.")
        mean = sum(values) / n
        sem = 0.0
        if n > 1:
            variance = sum((v - mean) ** 2 for v in values) / (n - 1)
            sem = (variance ** 0.5) / (n ** 0.5)
        return {cls}AggregatedResult(
            mean_value=mean,
            sem_value=sem,
            replicate_values=values,
        )

    # -- comparison ----------------------------------------------------------

    def extract_metrics(self, summary: Any) -> dict[str, MetricValue]:
        """Expose scalar metrics for the default comparison pipeline.

        ``AggregatedResultClass`` is set, so the framework always
        deserializes into ``{cls}AggregatedResult`` — no dict fallback needed.
        """
        return {{
            "value": MetricValue(
                name="value",
                mean=float(summary.mean_value),
                sem=float(summary.sem_value),
                replicate_values=[float(v) for v in summary.replicate_values],
                higher_is_better=True,
                direction_labels=("decreased", "unchanged", "increased"),
            )
        }}

    # -- formatting ----------------------------------------------------------

    def format(self, result: Any, output_format: str = "text") -> str:
        """Format comparison result for CLI display."""
        if isinstance(result, ComparisonResult):
            return format_scalar_comparison(
                result,
                title="{name.replace("_", " ").title()} Comparison",
                metric_label="Mean Value",
                metric_unit="",
                metric_key="value",
                output_format=output_format,
                higher_is_better=True,
            )
        return super().format(result, output_format)

    # -- plotting ------------------------------------------------------------

    def plot(self, ctx: PlotContext) -> list[Path]:
        """Generate comparison figures.

        Uses ``_build_plot_data()`` from the ``Analysis`` base class to
        load aggregated results for each condition, then creates a bar
        chart.  Replace this with your own plotting logic.

        As your plugin grows, extract plotting functions into a
        ``_plotters.py`` module within the package.
        """
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        from polyzymd.analyses.shared import apply_axis_style, get_colors, get_output_path, save_figure

        # _build_plot_data() collects analysis_dir / aggregated_dir per condition
        data, labels = self._build_plot_data(ctx)
        if not labels:
            return []

        # Collect per-condition aggregated values
        means: list[float] = []
        sems: list[float] = []
        valid_labels: list[str] = []
        for label in labels:
            if label not in data or label == "__meta__":
                continue
            agg_dir = data[label]["aggregated_dir"]
            summary = self._load_aggregated_result(agg_dir)
            if summary is None:
                continue
            means.append(float(summary.mean_value))
            sems.append(float(summary.sem_value))
            valid_labels.append(label)

        if not valid_labels:
            return []

        plot_settings = ctx.plot_settings
        colors = get_colors(len(valid_labels), plot_settings)

        fig, ax = plt.subplots(figsize=(8, 5))
        ax.bar(valid_labels, means, yerr=sems, capsize=5, color=colors[: len(valid_labels)])
        apply_axis_style(ax, plot_settings, title="{name.replace("_", " ").title()} Comparison", ylabel="Value")

        output_path = get_output_path(ctx.output_dir, "{name}_comparison", plot_settings)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        save_figure(fig, output_path, plot_settings)
        return [output_path]
'''


def _test_file_pydantic(name: str, cls: str) -> str:
    return f'''"""Tests for the {name} analysis plugin (pydantic style)."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from polyzymd.analyses.base import (
    AggregateContext,
    Condition,
    MetricValue,
    PlotContext,
    ReplicateContext,
)
from polyzymd.analyses.discovery import clear_cache, get_analysis
from polyzymd.analyses.{name} import (
    {cls}AggregatedResult,
    {cls}Analysis,
    {cls}ReplicateResult,
)
from polyzymd.analyses.shared import PlotSettings


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def analysis() -> {cls}Analysis:
    return {cls}Analysis()


@pytest.fixture
def settings():
    return {cls}Analysis.Settings()


@pytest.fixture
def plot_settings() -> PlotSettings:
    return PlotSettings()


@pytest.fixture
def condition(tmp_path: Path) -> Condition:
    return Condition(
        label="Condition A",
        config_path=tmp_path / "config.yaml",
        replicates=(1, 2),
        sim_config=MagicMock(),
    )


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------


class TestDiscovery:
    def test_discoverable_by_name(self):
        clear_cache()
        assert get_analysis("{name}") is {cls}Analysis

    def test_class_name(self):
        assert {cls}Analysis.name == "{name}"

    def test_settings_type(self):
        assert hasattr({cls}Analysis, "Settings")


# ---------------------------------------------------------------------------
# Compute
# ---------------------------------------------------------------------------


class TestComputeReplicate:
    def test_returns_typed_result(self, analysis, settings, condition, tmp_path):
        ctx = ReplicateContext(
            condition=condition,
            replicate=1,
            sim_config=condition.sim_config,
            output_dir=tmp_path / "run_1",
            equilibration="0ns",
            recompute=True,
            settings=settings,
        )
        result = analysis.compute_replicate(ctx, 1)

        assert isinstance(result, {cls}ReplicateResult)
        assert result.replicate == 1
        assert result.value == pytest.approx(1.0)
        assert result.example_parameter == "dummy"


# ---------------------------------------------------------------------------
# Aggregate
# ---------------------------------------------------------------------------


class TestAggregate:
    def test_aggregate_two_replicates(self, analysis, settings, condition, tmp_path):
        ctx = AggregateContext(
            condition=condition,
            replicates=(1, 2),
            output_dir=tmp_path / "aggregated",
            equilibration="0ns",
            settings=settings,
        )
        results = [
            {cls}ReplicateResult(replicate=1, value=1.0),
            {cls}ReplicateResult(replicate=2, value=3.0),
        ]
        summary = analysis.aggregate(ctx, results)

        assert isinstance(summary, {cls}AggregatedResult)
        assert summary.mean_value == pytest.approx(2.0)
        assert summary.replicate_values == [1.0, 3.0]


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


class TestExtractMetrics:
    def test_returns_metric_value(self, analysis):
        summary = {cls}AggregatedResult(
            mean_value=2.0,
            sem_value=0.5,
            replicate_values=[1.0, 3.0],
        )
        metrics = analysis.extract_metrics(summary)

        assert "value" in metrics
        assert isinstance(metrics["value"], MetricValue)
        assert metrics["value"].mean == pytest.approx(2.0)
        assert metrics["value"].sem == pytest.approx(0.5)


# ---------------------------------------------------------------------------
# Plot
# ---------------------------------------------------------------------------


class TestPlot:
    def test_plot_produces_figure(self, analysis, settings, plot_settings, tmp_path):
        """Plot with two conditions produces a comparison PNG."""
        conditions = []
        analysis_dirs = {{}}

        for label, mean, sem in [("Cond_A", 2.0, 0.3), ("Cond_B", 4.0, 0.5)]:
            cond = Condition(
                label=label,
                config_path=tmp_path / "config.yaml",
                replicates=(1, 2),
                sim_config=MagicMock(),
            )
            conditions.append(cond)

            agg_dir = tmp_path / label / "{name}" / "aggregated"
            agg_dir.mkdir(parents=True)
            (agg_dir / "result.json").write_text(
                json.dumps({{
                    "mean_value": mean,
                    "sem_value": sem,
                    "replicate_values": [mean - 0.1, mean + 0.1],
                }}),
                encoding="utf-8",
            )
            analysis_dirs[label] = tmp_path / label / "{name}"

        ctx = PlotContext(
            conditions=conditions,
            analysis_dirs=analysis_dirs,
            output_dir=tmp_path / "figures",
            results_dir=tmp_path / "results",
            settings=settings,
            plot_settings=plot_settings,
        )

        paths = analysis.plot(ctx)

        assert len(paths) == 1
        assert paths[0].exists()
        assert paths[0].suffix == ".png"

    def test_plot_returns_empty_when_no_data(self, analysis, settings, plot_settings, tmp_path):
        """Plot with no aggregated results returns empty list."""
        cond = Condition(
            label="Empty",
            config_path=tmp_path / "config.yaml",
            replicates=(1,),
            sim_config=MagicMock(),
        )
        analysis_dirs = {{"Empty": tmp_path / "Empty" / "{name}"}}
        (tmp_path / "Empty" / "{name}" / "aggregated").mkdir(parents=True)

        ctx = PlotContext(
            conditions=[cond],
            analysis_dirs=analysis_dirs,
            output_dir=tmp_path / "figures",
            results_dir=tmp_path / "results",
            settings=settings,
            plot_settings=plot_settings,
        )

        paths = analysis.plot(ctx)
        assert paths == []
'''


# ---------------------------------------------------------------------------
# Template dispatch
# ---------------------------------------------------------------------------

_PLUGIN_TEMPLATES = {
    "dict": _plugin_init_dict,
    "pydantic": _plugin_init_pydantic,
}

_TEST_TEMPLATES = {
    "dict": _test_file_dict,
    "pydantic": _test_file_pydantic,
}


# ---------------------------------------------------------------------------
# File generation
# ---------------------------------------------------------------------------


def generate_scaffold(
    name: str,
    project_root: Path,
    *,
    class_name: str | None = None,
    style: str = "dict",
    force: bool = False,
    dry_run: bool = False,
) -> list[Path]:
    """Create scaffold files for a new analysis plugin.

    Parameters
    ----------
    name : str
        Plugin name in snake_case (e.g. ``"solvent_shell"``).
    project_root : Path
        Repository root directory (contains ``src/`` and ``tests/``).
    class_name : str or None
        PascalCase class prefix.  Auto-derived from *name* if not given.
    style : str
        ``"dict"`` (default) for plain-dict results, or ``"pydantic"``
        for typed Pydantic result models.
    force : bool
        Overwrite existing files.
    dry_run : bool
        Print paths without writing files.

    Returns
    -------
    list[Path]
        Paths of created (or would-be-created) files.
    """
    # Validate style
    if style not in VALID_STYLES:
        raise ValueError(f"Invalid style '{style}'. Choose from: {', '.join(VALID_STYLES)}")

    # Validate the plugin name — always check for name collisions with
    # existing plugins/aliases, even with --force.  The --force flag only
    # allows overwriting *files*, not reusing a registered plugin name.
    name_error = validate_name(name, check_existing=True)
    if name_error:
        raise ValueError(name_error)

    cls = class_name or to_pascal_case(name)

    # Validate the class name (whether user-supplied or auto-derived)
    cls_error = validate_class_name(cls)
    if cls_error:
        raise ValueError(cls_error)

    analyses_dir = project_root / "src" / "polyzymd" / "analyses" / name
    tests_dir = project_root / "tests"

    plugin_template = _PLUGIN_TEMPLATES[style]
    test_template = _TEST_TEMPLATES[style]

    files: dict[Path, str] = {
        analyses_dir / "__init__.py": plugin_template(name, cls),
        tests_dir / "analyses" / "plugins" / f"test_{name}.py": test_template(name, cls),
    }

    created: list[Path] = []
    for path, content in files.items():
        if path.exists() and not force:
            raise FileExistsError(f"{path} already exists. Use --force to overwrite.")
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        created.append(path)

    return created
