"""Backward-compatibility shim — canonical location is ``polyzymd.analyses._contacts_binding_preference``.

All public names are re-exported so that existing ``from polyzymd.analysis.contacts.binding_preference
import …`` statements continue to work during the migration period.
"""

from polyzymd.analyses._contacts_binding_preference import (  # noqa: F401
    AggregatedBindingPreferenceEntry,
    AggregatedBindingPreferenceResult,
    AggregatedPartitionBindingEntry,
    AggregatedPartitionBindingResult,
    AggregatedPartitionCoverageEntry,
    AggregatedPartitionCoverageResult,
    AggregatedPolymerBindingPreferenceResult,
    AggregatedSystemCoverageResult,
    BindingPreferenceEntry,
    BindingPreferenceResult,
    PartitionBindingEntry,
    PartitionBindingResult,
    PartitionCoverageEntry,
    PartitionCoverageResult,
    PolymerBindingPreferenceResult,
    PolymerComposition,
    SystemCoverageEntry,
    SystemCoverageResult,
    aggregate_binding_preference,
    aggregate_polymer_binding_preference,
    aggregate_system_coverage,
    compute_binding_preference,
    compute_binding_preference_from_config,
    extract_polymer_composition,
    resolve_polymer_type_selections,
    resolve_protein_group_selections,
    resolve_protein_groups_from_surface_exposure,
)

__all__ = [
    "AggregatedBindingPreferenceEntry",
    "AggregatedBindingPreferenceResult",
    "AggregatedPartitionBindingEntry",
    "AggregatedPartitionBindingResult",
    "AggregatedPartitionCoverageEntry",
    "AggregatedPartitionCoverageResult",
    "AggregatedPolymerBindingPreferenceResult",
    "AggregatedSystemCoverageResult",
    "BindingPreferenceEntry",
    "BindingPreferenceResult",
    "PartitionBindingEntry",
    "PartitionBindingResult",
    "PartitionCoverageEntry",
    "PartitionCoverageResult",
    "PolymerBindingPreferenceResult",
    "PolymerComposition",
    "SystemCoverageEntry",
    "SystemCoverageResult",
    "aggregate_binding_preference",
    "aggregate_polymer_binding_preference",
    "aggregate_system_coverage",
    "compute_binding_preference",
    "compute_binding_preference_from_config",
    "extract_polymer_composition",
    "resolve_polymer_type_selections",
    "resolve_protein_group_selections",
    "resolve_protein_groups_from_surface_exposure",
]
