"""Trajectory analysis module for PolyzyMD.

This module provides tools for analyzing MD simulation trajectories
generated by PolyzyMD, with proper statistical handling across
multiple replicates.

Submodules
----------
core
    Infrastructure: config hashing, statistics, autocorrelation, loading
results
    Pydantic models for analysis results
rmsf
    RMSF (Root Mean Square Fluctuation) analysis
distances
    Inter-atomic distance analysis

Quick Start
-----------
>>> from polyzymd.config import load_config
>>> from polyzymd.analysis import RMSFCalculator, DistanceCalculator
>>>
>>> config = load_config("config.yaml")
>>>
>>> # RMSF analysis
>>> rmsf_calc = RMSFCalculator(config, selection="protein and name CA", equilibration="100ns")
>>> result = rmsf_calc.compute_aggregated(replicates=[1, 2, 3, 4, 5])
>>> print(f"RMSF: {result.overall_mean_rmsf:.2f} ± {result.overall_sem_rmsf:.2f} Å")
>>>
>>> # Distance analysis
>>> pairs = [("resid 77 and name OG", "resid 133 and name NE2")]
>>> dist_calc = DistanceCalculator(config, pairs=pairs, equilibration="100ns")
>>> result = dist_calc.compute(replicate=1)

Installation
------------
Analysis tools require optional dependencies:

    pip install polyzymd[analysis]

This installs MDAnalysis and matplotlib.
"""


# Lazy imports to avoid loading MDAnalysis unless needed
def __getattr__(name):
    """Lazy import of analysis components."""
    if name == "RMSFCalculator":
        from polyzymd.analysis.rmsf import RMSFCalculator

        return RMSFCalculator
    elif name == "DistanceCalculator":
        from polyzymd.analysis.distances import DistanceCalculator

        return DistanceCalculator
    elif name == "TrajectoryLoader":
        from polyzymd.analysis.core.loader import TrajectoryLoader

        return TrajectoryLoader
    elif name == "compute_config_hash":
        from polyzymd.analysis.core.config_hash import compute_config_hash

        return compute_config_hash
    elif name == "validate_config_hash":
        from polyzymd.analysis.core.config_hash import validate_config_hash

        return validate_config_hash
    elif name in ("plot_rmsf", "plot_rmsf_comparison", "save_rmsf_plot"):
        from polyzymd.analysis import rmsf

        return getattr(rmsf, name)
    elif name in ("plot_distance_histogram", "plot_distance_comparison", "save_distance_plot"):
        from polyzymd.analysis import distances

        return getattr(distances, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    # Calculators
    "RMSFCalculator",
    "DistanceCalculator",
    # Loading
    "TrajectoryLoader",
    # Config validation
    "compute_config_hash",
    "validate_config_hash",
    # Plotting (RMSF)
    "plot_rmsf",
    "plot_rmsf_comparison",
    "save_rmsf_plot",
    # Plotting (Distances)
    "plot_distance_histogram",
    "plot_distance_comparison",
    "save_distance_plot",
]
